<?php

namespace Util;

class OracleQuery {

		public function getArray() {
				return self::QUERY_MAPPING;
		}

		const QUERY_MAPPING = array(
			'SQL_INSERE_VENDA_REST'                    => self::SQL_INSERE_VENDA_REST,
			'SQL_INSERE_VENDAREST'                     => self::SQL_INSERE_VENDAREST,
			'SQL_GET_NRSEQCOM'                         => self::SQL_GET_NRSEQCOM,
			'SQL_GET_UNGROUPED_TABLES'                 => self::SQL_GET_UNGROUPED_TABLES,
			'SQL_GET_NRJUNMESA'                        => self::SQL_GET_NRJUNMESA,
			'SQL_BUSCA_NRCOMANDA'                      => self::SQL_BUSCA_NRCOMANDA,
			'SQL_FIX_NOVOCODIGO'                       => self::SQL_FIX_NOVOCODIGO,
            'SQL_PREPARE_FIX_NOVOCODIGO'               => self::SQL_PREPARE_FIX_NOVOCODIGO,
			'SQL_MAX_CHAMADA'                          => self::SQL_MAX_CHAMADA,
			'SQL_GET_CALL'                             => self::SQL_GET_CALL,
			'SQL_ITENS_COMANDAS'                       => self::SQL_ITENS_COMANDAS,
			'SQL_SELECIONA_ITEM'                       => self::SQL_SELECIONA_ITEM,
			'SQL_ITENS_COMANDA'                        => self::SQL_ITENS_COMANDA,
			'SQL_INSERE_ITEM_POSICAO'                  => self::SQL_INSERE_ITEM_POSICAO,
			'SQL_SELECIONA_VALORES'                    => self::SQL_SELECIONA_VALORES,
			'SQL_VALIDA_VALORES'                       => self::SQL_VALIDA_VALORES,
			'SQL_VALIDA_VALORES_ITEM'                  => self::SQL_VALIDA_VALORES_ITEM,
			'SQL_VALIDA_VALORES_ORIG'                  => self::SQL_VALIDA_VALORES_ORIG,
			'SQL_GET_DELAYED_PRODUCTS'                 => self::SQL_GET_DELAYED_PRODUCTS,
			'SQL_GET_ALL_CONSUMERS_BY_CLIENT'          => self::SQL_GET_ALL_CONSUMERS_BY_CLIENT,
			'SQL_GET_CONSUMERS_BY_CLIENT'              => self::SQL_GET_CONSUMERS_BY_CLIENT,
			'SQL_VERIFICA_IP_BLOQUEADO'                => self::SQL_VERIFICA_IP_BLOQUEADO,
			'SQL_BUSCA_IPS_BLOQUEADOS'                 => self::SQL_BUSCA_IPS_BLOQUEADOS,
			'SQL_LISTA_COMANDA'                        => self::SQL_LISTA_COMANDA,
			'SQL_CONSULTA_MESA'                        => self::SQL_CONSULTA_MESA,
			'SQL_DATA_ABERTURA'                        => self::SQL_DATA_ABERTURA,
			'GET_TABLES_WITH_DELAYED_ITEMS'            => self::GET_TABLES_WITH_DELAYED_ITEMS,
			'BUSCA_MESAS_AGRUPADAS'                    => self::BUSCA_MESAS_AGRUPADAS,
			'SQL_ITENS_DETALHADOS'                     => self::SQL_ITENS_DETALHADOS,
			'SQL_ITENS_ITCOMANDAEST'                   => self::SQL_ITENS_ITCOMANDAEST,
			'SQL_UPDATE_MOVCAIXAMOB'                   => self::SQL_UPDATE_MOVCAIXAMOB,
			'SQL_INSERT_MOVCAIXAMOB'                   => self::SQL_INSERT_MOVCAIXAMOB,
			'SQL_GET_MAIN_PRODUCT'                     => self::SQL_GET_MAIN_PRODUCT,
			'SQL_GET_PRODUCT_COMPOSITION'              => self::SQL_GET_PRODUCT_COMPOSITION,
			'SQL_ACESSOS'                              => self::SQL_ACESSOS,
			'SQL_ACESSOS_AUT'                          => self::SQL_ACESSOS_AUT,
			'SQL_DADOS_CAIXA'                          => self::SQL_DADOS_CAIXA,
			'SQL_BD_VERSION'                           => self::SQL_BD_VERSION,
			'SQL_TEMPO_PERMANENCIA'                    => self::SQL_TEMPO_PERMANENCIA,
			'SQL_PRODUTOS_PARCIAL'                     => self::SQL_PRODUTOS_PARCIAL,
			'SQL_PRODUTOS_PARCIAL_NUMERO_PRODUTOS'     => self::SQL_PRODUTOS_PARCIAL_NUMERO_PRODUTOS,
			'SQL_POSICAO_PARCIAL'                      => self::SQL_POSICAO_PARCIAL,
			'SQL_ITENS_DETALHADOS_SEM_COMBO'           => self::SQL_ITENS_DETALHADOS_SEM_COMBO,
			'SQL_ITENS_ORIGINAIS'                      => self::SQL_ITENS_ORIGINAIS,
			'SQL_INSERE_ACESSO'                        => self::SQL_INSERE_ACESSO,
			'SQL_UPDATE_ACESSO'                        => self::SQL_UPDATE_ACESSO,
			'TABELA_VENDA'                             => self::TABELA_VENDA,
			'SQL_MOVER_TRANSACOES'                     => self::SQL_MOVER_TRANSACOES,
			'SQL_BUSCA_TRANSACOES_TEMPO'               => self::SQL_BUSCA_TRANSACOES_TEMPO,
			'SQL_BUSCA_TRANSACOES_ENTRADA_MOVCAIXA'    => self::SQL_BUSCA_TRANSACOES_ENTRADA_MOVCAIXA,
			'SQL_BUSCA_TRANSACOES_SAIDA_MOVCAIXA'      => self::SQL_BUSCA_TRANSACOES_SAIDA_MOVCAIXA,
			'SQL_BUSCA_TRANSACOES_MESA_MOVCAIXAMOB'    => self::SQL_BUSCA_TRANSACOES_MESA_MOVCAIXAMOB,
			'SQL_BUSCA_TRANSACOES_POSICAO_MOVCAIXAMOB' => self::SQL_BUSCA_TRANSACOES_POSICAO_MOVCAIXAMOB,
			'SQL_DADOS_ITEM_COMANDA'                   => self::SQL_DADOS_ITEM_COMANDA,
			'SQL_INSERE_LOG'                           => self::SQL_INSERE_LOG,
			'SQL_DADOS_COMANDA_ABERTURA'               => self::SQL_DADOS_COMANDA_ABERTURA,
			'SQL_FILIAIS'                              => self::SQL_FILIAIS,
			'SQL_CAIXAS'                               => self::SQL_CAIXAS,
			'SQL_VENDEDORES'                           => self::SQL_VENDEDORES,
			'SQL_GET_PRODUCT_DESC'                     => self::SQL_GET_PRODUCT_DESC,
			'SQL_BUSCA_CONSUMIDORES'                   => self::SQL_BUSCA_CONSUMIDORES,
			'SQL_CONSUMER_CDEXCONSUMID'                => self::SQL_CONSUMER_CDEXCONSUMID,
			'SQL_CONSUMER_CDIDCONSUMID'                => self::SQL_CONSUMER_CDIDCONSUMID,
			'SQL_CONSUMER_NRCPFRESPCON'                => self::SQL_CONSUMER_NRCPFRESPCON,
			'SQL_GET_CONSUMER_DETAILS'                 => self::SQL_GET_CONSUMER_DETAILS,
			'GET_ULTIMA_VENDA_FISCAL'                  => self::GET_ULTIMA_VENDA_FISCAL,
			'GET_VENDA'                                => self::GET_VENDA,
			'SQL_CHECK_ORDERCODE'                      => self::SQL_CHECK_ORDERCODE,
			'FILTRAR_PRODUTOS'                         => self::FILTRAR_PRODUTOS,
			'GET_VENDAS'                               => self::GET_VENDAS,
			'SQL_COMANDA_ITENS'                        => self::SQL_COMANDA_ITENS,
			'BUSCA_DADOS_CAMPANHA'                     => self::BUSCA_DADOS_CAMPANHA,
			'GET_REGISTER_CLOSING_PAY_N'               => self::GET_REGISTER_CLOSING_PAY_N,
			'GET_DELIVERY_ORDERS'                      => self::GET_DELIVERY_ORDERS,
			'GET_DELIVERY_ORDERS_CONTROL'              => self::GET_DELIVERY_ORDERS_CONTROL,
			'GET_ORDER_PARAMS_DLV'					   => self::GET_ORDER_PARAMS_DLV,
			'GET_PRODUTOS_PEDIDODLV'				   => self::GET_PRODUTOS_PEDIDODLV,
    		'UPDATE_VRCOMISVENDE'                      => self::UPDATE_VRCOMISVENDE
		);

		const SQL_INSERE_VENDA_REST = "
				INSERT INTO VENDAREST
						(CDFILIAL, NRVENDAREST, CDLOJA, NRMESA,
						CDVENDEDOR, DTHRABERMESA, CDOPERADOR, NRPESMESAVEN,
						CDCLIENTE, CDCONSUMIDOR, NRORG)
				VALUES
						(:CDFILIAL, :NRVENDAREST, :CDLOJA, :NRMESA,
						:CDVENDEDOR, SYSDATE, :CDOPERADOR, :NRPESMESAVEN,
						:CDCLIENTE, :CDCONSUMIDOR, :NRORG)
		";

		const SQL_INSERE_VENDAREST = "
			INSERT INTO VENDAREST
					(CDFILIAL, NRVENDAREST, CDLOJA, NRMESA,
					CDVENDEDOR, DTHRABERMESA, CDOPERADOR, NRPESMESAVEN,
					CDCLIENTE, CDCONSUMIDOR, NRPOSICAOMESA, NRORG)
			VALUES
					(:CDFILIAL, :NRVENDAREST, :CDLOJA, :NRMESA,
					:CDVENDEDOR, SYSDATE, :CDOPERADOR, :NRPESMESAVEN,
					:CDCLIENTE, :CDCONSUMIDOR, :NRPOSICAOMESA, :NRORG)
		";

		const SQL_GET_NRSEQCOM = "
		SELECT NRSEQPRODCOM
			FROM (SELECT NVL(MAX(NRSEQPRODCOM),0) AS NRSEQPRODCOM
							FROM ITCOMANDAVEN
						 WHERE CDFILIAL    = :CDFILIAL
							 AND NRVENDAREST = :NRVENDAREST
							 AND NRCOMANDA   = :NRCOMANDA
							 AND NRORG       = :NRORG
							 AND NRSEQPRODCOM IS NOT NULL) A
		";

		const SQL_GET_UNGROUPED_TABLES = "
				SELECT NRMESA
					FROM MESA
				 WHERE CDFILIAL = :CDFILIAL
					 AND CDLOJA   = :CDLOJA
					 AND NRORG    = :NRORG
					 AND (INSTR(:PARAM, NRMESA) > 0)
					 AND NRMESA NOT IN (SELECT NRMESA
																FROM MESAJUNCAO
															 WHERE CDFILIAL = :CDFILIAL
																 AND CDLOJA   = :CDLOJA
																 AND NRORG    = :NRORG
																 AND (INSTR(:PARAM, NRMESA) > 0))
		";

		const SQL_GET_NRJUNMESA = "
				SELECT NRJUNMESA
					FROM MESAJUNCAO
				 WHERE CDFILIAL = :CDFILIAL
					 AND CDLOJA = :CDLOJA
					 AND (INSTR(:PARAM, NRMESA) > 0)
		";

        const SQL_BUSCA_NRCOMANDA = "
            SELECT CV.NRCOMANDA, CV.NRVENDAREST, VR.NRMESA, VR.NRPESMESAVEN
              FROM COMANDAVEN CV JOIN VENDAREST VR
                                   ON CV.CDFILIAL = VR.CDFILIAL
                                  AND CV.NRVENDAREST = VR.NRVENDAREST
                                  AND CV.NRORG = VR.NRORG
             WHERE CV.CDFILIAL = :CDFILIAL
               AND CV.NRORG = :NRORG
               AND INSTR(:PARAM, VR.NRMESA) > 0
        ";

        const SQL_PREPARE_FIX_NOVOCODIGO = "
            SELECT NRSEQUENCIAL
              FROM NOVOCODIGO
             WHERE CDCONTADOR = :CDCONTADOR
               AND LENGTH(CDCONTADOR) > 16
               AND NRORG = :NRORG
        ";

        const SQL_FIX_NOVOCODIGO = "
            UPDATE NOVOCODIGO
               SET NRSEQUENCIAL = :NRSEQUENCIAL
             WHERE CDCONTADOR = :CDCONTADOR
               AND LENGTH(CDCONTADOR) > 16
               AND NRORG = :NRORG
        ";

		const SQL_MAX_CHAMADA = "
				SELECT NVL(MAX(NRCHAMADA), '0000000001') AS NRCHAMADA
					FROM CHAMADAWAITER
				 WHERE NRACESSOUSER = ?
		";

		const SQL_GET_CALL = "
				SELECT NMUSUARIO, A.NRMESA, IDTIPOCHAMADA,
							 TRUNC((C.DTULTATU - SYSDATE) * 60 * 60 * 24) AS TEMPO,
							 C.NRACESSOUSER, M.NMMESA
					FROM CHAMADAWAITER C, ACESSOFM A, MESA M
				 WHERE C.NRACESSOUSER = A.NRACESSOUSER
					 AND A.NRMESA = M.NRMESA
					 AND A.IDACESSOUSER = 'A'
					 AND C.IDSTCHAMADA = 'P'
		";

		const SQL_ITENS_COMANDAS = "
				SELECT IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRPRECCOMVEN, TO_CHAR(IT.TXPRODCOMVEN) AS TXPRODCOMVEN,
							 IT.IDSTPRCOMVEN, NVL(IT.VRDESCCOMVEN,0) AS VRDESCCOMVEN, PR.CDARVPROD, PR.NMPRODUTO,
							 IT.CDPRODUTO, IT.DTHRINCOMVEN, PR.IDCOBTXSERV, IT.NRCOMANDA, NVL(IT.VRPRECCLCOMVEN,0) AS VRPRECCLCOMVEN,
							 IT.NRVENDAREST, NVL(IT.VRACRCOMVEN,0) AS VRACRCOMVEN, IT.NRSEQPRODCOM
					FROM ITCOMANDAVEN IT, PRODUTO PR
				 WHERE IT.CDFILIAL = ?
					 AND (INSTR(?, IT.NRCOMANDA) > 0)
					 AND IT.CDPRODUTO = PR.CDPRODUTO
					 AND IT.IDSTPRCOMVEN NOT IN ('7')
		";

		const SQL_SELECIONA_ITEM = "
				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) AS TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT. NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA, IT.NRPRODORIG, IT.IDDIVIDECONTA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (IT.NRCOMANDA = ?)
					AND (IT.NRVENDAREST = ?)
					AND (IT.NRPRODCOMVEN = ?)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON,TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.NRPRODORIG, IT.IDDIVIDECONTA

				UNION

				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST,
					IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO,
					IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) AS TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA, IT.NRPRODORIG, IT.IDDIVIDECONTA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (IT.NRCOMANDA = ?)
					AND (IT.NRVENDAREST = ?)
					AND (IT.NRPRODCOMVEN = ?)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'S')
					AND ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON, TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.NRPRODORIG, IT.IDDIVIDECONTA
		";

		const SQL_ITENS_COMANDA = "
				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT. NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN, 'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN, 'HH24:MI:SS') AS HORA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (IT.NRCOMANDA = ?)
					AND (IT.NRVENDAREST = ?)
					AND (IT.NRPRODCOMVEN = ?)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON,TO_CHAR(IT.DTHRINCOMVEN, 'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN, 'HH24:MI:SS')

				UNION

				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST,
					IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO,
					IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN, 'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (IT.NRCOMANDA = ?)
					AND (IT.NRVENDAREST = ?)
					AND (IT.NRPRODCOMVEN = ?)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'S')
					AND ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON, TO_CHAR(IT.DTHRINCOMVEN, 'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS')
		";

		const SQL_INSERE_ITEM_POSICAO = "
			 INSERT INTO
						ITCOMANDAVEN
					(CDFILIAL, NRVENDAREST, NRCOMANDA, NRPRODCOMVEN, CDPRODUTO, QTPRODCOMVEN, VRPRECCOMVEN, TXPRODCOMVEN, IDSTPRCOMVEN,
					VRDESCCOMVEN, NRLUGARMESA, DTHRINCOMVEN, IDPRODIMPFIS, CDLOJA, VRACRCOMVEN, NRSEQPRODCOM, NRSEQPRODCUP, CDCAIXACOLETOR,
					VRPRECCLCOMVEN, CDPRODPROMOCAO, CDVENDEDOR, CDSENHAPED, DSOBSPEDDIGCMD, IDORIGPEDCMD, IDDIVIDECONTA, NRPRODORIG, IDPRODREFIL,
					QTITEMREFIL, NRPEDIDOFOS)
							SELECT
					CDFILIAL, NRVENDAREST, NRCOMANDA, ?, CDPRODUTO, ?, VRPRECCOMVEN, TXPRODCOMVEN, IDSTPRCOMVEN, ?, ?, SYSDATE, IDPRODIMPFIS,
					CDLOJA, ?, NRSEQPRODCOM, NRSEQPRODCUP, CDCAIXACOLETOR, VRPRECCLCOMVEN, CDPRODPROMOCAO, CDVENDEDOR, CDSENHAPED, DSOBSPEDDIGCMD,
					IDORIGPEDCMD, 'S', ?, IDPRODREFIL, QTITEMREFIL, NRPEDIDOFOS
							FROM
					ITCOMANDAVEN
							WHERE
					CDFILIAL = ? AND NRVENDAREST = ? AND NRCOMANDA = ? AND NRPRODCOMVEN = ?
		";

		const SQL_SELECIONA_VALORES = "
				SELECT SUM(NVL(VRDESCCOMVEN,0)) AS VRDESCCOMVEN, SUM(NVL(VRACRCOMVEN,0)) AS VRACRCOMVEN,
								 SUM(NVL(QTPRODCOMVEN,0)) AS QTPRODCOMVEN
				FROM ITCOMANDAVEN
			 WHERE (CDFILIAL      = ? )
				 AND (NRVENDAREST   = ? )
				 AND (NRCOMANDA     = ? )
				 AND (IDDIVIDECONTA = 'S' )
				 AND ((NRPRODORIG = ? ) OR (?  = 'T'))
		";

		const SQL_VALIDA_VALORES = "
				SELECT NRPRODCOMVEN, (ROUND(QTPRODCOMVEN * VRPRECCOMVEN,2) - NVL(VRDESCCOMVEN,0) + NVL(VRACRCOMVEN,0)) AS VRTOTAL
					FROM ITCOMANDAVEN
				 WHERE (CDFILIAL      = ?   )
					 AND (NRVENDAREST   = ?   )
					 AND (NRCOMANDA     = ?   )
					 AND (NRPRODORIG    = ?   )
					 AND (IDDIVIDECONTA = 'S' )
		";

		const SQL_VALIDA_VALORES_ITEM = "
				SELECT SUM(NVL(VRDESCCOMVEN,0)) AS VRDESCCOMVEN, SUM(NVL(VRACRCOMVEN,0)) AS VRACRCOMVEN,
						 SUM(NVL(QTPRODCOMVEN,0)) AS QTPRODCOMVEN
				FROM ITCOMANDAVEN
				WHERE (CDFILIAL       = ? )
					AND (NRVENDAREST    = ? )
					AND (NRCOMANDA      = ? )
					AND (NRPRODORIG  = ? )
					AND (IDDIVIDECONTA  = 'S' )
		";

		const SQL_VALIDA_VALORES_ORIG = "
				SELECT SUM(NVL(VRDESCCOMVEN,0)) AS VRDESCCOMVEN, SUM(NVL(VRACRCOMVEN,0)) AS VRACRCOMVEN,
						 SUM(NVL(QTPRODCOMVEN,0)) AS QTPRODCOMVEN
				FROM ITCMDVENORIG
				WHERE   (CDFILIAL     = ? )
						AND (NRVENDAREST  = ? )
						AND (NRCOMANDA    = ? )
						AND (NRPRODCOMVEN  = ? )
		";


		const SQL_GET_DELAYED_PRODUCTS = "
				SELECT I.CDFILIAL, I.NRPEDIDOFOS, I.NRITPEDIDOFOS,
							 V.NRVENDAREST, V.NRCOMANDA, V.NRPRODCOMVEN,
							 V.CDPRODUTO, P.NMPRODUTO AS DSBUTTON, V.NRSEQPRODCOM,
							 V.NRLUGARMESA AS 'POSITION', V.NRLUGARMESA AS 'POS',
							 SUBSTR(TO_CHAR(V.DTHRINCOMVEN, 'DD/MM/AAAA'), 1, 5) AS DTHRINCOMVEN,
							 V.CDPRODPROMOCAO
					FROM ITPEDIDOFOSREL R JOIN ITPEDIDOFOS I
																	ON I.CDFILIAL = R.CDFILIAL
																 AND I.NRPEDIDOFOS = R.NRPEDIDOFOS
																 AND I.NRITPEDIDOFOS = R.NRITPEDIDOFOS

																JOIN ITCOMANDAVEN V
																	ON V.CDFILIAL = R.CDFILIAL
																 AND V.NRVENDAREST = R.NRVENDAREST
																 AND V.NRCOMANDA = R.NRCOMANDA
																 AND V.NRPRODCOMVEN = R.NRPRODCOMVEN

																JOIN SETOR S
																	ON S.CDSETOR = I.CDSETOR

																JOIN PRODUTO P
																	ON P.CDPRODUTO = I.CDPRODUTO

				 WHERE S.IDTIPOSETOR = 'E'
					 AND I.IDLIBERADO = 'N'
					 AND I.NRATRAPRODITPE IS NOT NULL
					 AND V.NRATRAPRODCOVE IS NOT NULL
					 AND I.DTHREXIBICAOPROD > SYSDATE
					 AND V.CDFILIAL = :CDFILIAL
					 AND V.NRVENDAREST = :NRVENDAREST
					 AND V.NRCOMANDA = :NRCOMANDA
					 AND V.IDSTPRCOMVEN <> '6'
		";

				const SQL_GET_ALL_CONSUMERS_BY_CLIENT = "
				SELECT A.CDCLIENTE,  A.CDCONSUMIDOR,  A.NMCONSUMIDOR,
						A.VRLIMDEBCONS,  A.IDSITCONSUMI,  A.CDTIPOCONS,
						A.CDCCUSCLIE,    A.CDIDCONSUMID,  A.VRAVIDEBCONS,
						A.CDEXCONSUMID,  A.IDVERSALDCON,  A.IDCONSUMIDOR,
						A.CDVENDEDOR,    A.VRMAXDEBCONS,  A.VRLIMCREDCONS,
						A.VRMAXCREDCONS, A.VRAVICREDCONS, A.IDUTSUBTCCLI,
						A.VRPESUBTCCLI,  A.NRRGCONSUMID,  A.NRCPFRESPCON,
						A.NRTELECONS,    A.NRTELE2CONS,   A.IDTPVENDACONS,
						A.NMFANTCLIE,    A.CDFILIAL,      A.NMFILIAL,
						A.IDCLIENPRIN,   A.IDIMPCPFCUPOM, A.IDCADCONFLIBCON,
						A.DSENDECONS,    A.CDRESERVAPH,   A.DTCHECKINPH,
						A.DTCHECKOUTPH,  TO_CHAR(A.DSOBSHOSPEDEPH) AS DSOBSHOSPEDEPH
					FROM(
						 SELECT CO.CDCLIENTE,     CO.CDCONSUMIDOR,  CO.NMCONSUMIDOR,
										CO.VRLIMDEBCONS,  CO.IDSITCONSUMI,  CO.CDTIPOCONS,
										CO.CDCCUSCLIE,    CO.CDIDCONSUMID,  CO.VRAVIDEBCONS,
										CO.CDEXCONSUMID,  CO.IDVERSALDCON,  CO.IDCONSUMIDOR,
										CO.CDVENDEDOR,    CO.VRMAXDEBCONS,  CO.VRLIMCREDCONS,
										CO.VRMAXCREDCONS, CO.VRAVICREDCONS, CO.NRRGCONSUMID,
										CO.NRCPFRESPCON,  CO.NRTELECONS,    CO.NRTELE2CONS,
										T.IDUTSUBTCCLI,   T.VRPESUBTCCLI,   CO.IDTPVENDACONS,
										C.NMFANTCLIE,     F.CDFILIAL,       F.NMFILIAL,
										CF.IDCLIENPRIN,   CO.IDIMPCPFCUPOM, CO.IDCADCONFLIBCON,
										CO.DSENDECONS,    CO.CDRESERVAPH,   CO.DTCHECKINPH,
										CO.DTCHECKOUTPH,  TO_CHAR(CO.DSOBSHOSPEDEPH) AS DSOBSHOSPEDEPH
							 FROM CLIENFILIAL CF, CLIENTE C, FILIAL F,
										CONSUMIDOR CO LEFT JOIN TIPOCONSCLI T ON (CO.CDCLIENTE = T.CDCLIENTE)
																												 AND (CO.CDTIPOCONS = T.CDTIPOCONS)
							 JOIN TIPOCONS TC ON TC.CDTIPOCONS = CO.CDTIPOCONS
							WHERE (CF.CDCLIENTE  = CO.CDCLIENTE)
								AND (C.CDCLIENTE   = CO.CDCLIENTE)
								AND (C.CDCLIENTE = CF.CDCLIENTE)
								AND (CF.CDFILIAL = F.CDFILIAL)
								AND (CF.CDFILIAL   = ?)
								AND (CO.CDCLIENTE  = ?)
								AND (CF.IDPERMVENDAFOS = 'S')
								AND (CO.IDSITCONSUMI   = '1')
								AND (TC.IDDESABPESQCON = 'N')) A
				UNION
				SELECT B.CDCLIENTE,     B.CDCONSUMIDOR,  B.NMCONSUMIDOR,
							 B.VRLIMDEBCONS,  B.IDSITCONSUMI,  B.CDTIPOCONS,
							 B.CDCCUSCLIE,    B.CDIDCONSUMID,  B.VRAVIDEBCONS,
							 B.CDEXCONSUMID,  B.IDVERSALDCON,  B.IDCONSUMIDOR,
							 B.CDVENDEDOR,    B.VRMAXDEBCONS,  B.VRLIMCREDCONS,
							 B.VRMAXCREDCONS, B.VRAVICREDCONS, B.IDUTSUBTCCLI,
							 B.VRPESUBTCCLI,  B.NRRGCONSUMID,  B.NRCPFRESPCON,
							 B.NRTELECONS,    B.NRTELE2CONS,   B.IDTPVENDACONS,
							 B.NMFANTCLIE,    B.CDFILIAL,      B.NMFILIAL, B.IDCLIENPRIN,
							 B.IDIMPCPFCUPOM, B.IDCADCONFLIBCON, B.DSENDECONS,
							 B.CDRESERVAPH,   B.DTCHECKINPH,   B.DTCHECKOUTPH,
							 TO_CHAR(B.DSOBSHOSPEDEPH) AS DSOBSHOSPEDEPH
					FROM(
						 SELECT CO.CDCLIENTE,     CO.CDCONSUMIDOR,  CO.NMCONSUMIDOR,
										CO.VRLIMDEBCONS,  CO.IDSITCONSUMI,  CO.CDTIPOCONS,
										CO.CDCCUSCLIE,    CO.CDIDCONSUMID,  CO.VRAVIDEBCONS,
										CO.CDEXCONSUMID,  CO.IDVERSALDCON,  CO.IDCONSUMIDOR,
										CO.CDVENDEDOR,    CO.VRMAXDEBCONS,  CO.VRLIMCREDCONS,
										CO.VRMAXCREDCONS, CO.VRAVICREDCONS, CO.NRRGCONSUMID,
										CO.NRCPFRESPCON,  CO.NRTELECONS,    CO.NRTELE2CONS,
										T.IDUTSUBTCCLI,   T.VRPESUBTCCLI,   CO.IDTPVENDACONS,
										C.NMFANTCLIE, F.CDFILIAL, F.NMFILIAL,
										CF.IDCLIENPRIN, CO.IDIMPCPFCUPOM, CO.IDCADCONFLIBCON,
										CO.DSENDECONS,    CO.CDRESERVAPH,   CO.DTCHECKINPH,
										CO.DTCHECKOUTPH,  TO_CHAR(CO.DSOBSHOSPEDEPH) AS DSOBSHOSPEDEPH
							 FROM CONSUMIDOR CO
							 JOIN TIPOCONS TC ON TC.CDTIPOCONS = CO.CDTIPOCONS
							 LEFT JOIN TIPOCONSCLI T ON
								 (CO.CDCLIENTE  = T.CDCLIENTE)  AND
								 (CO.CDTIPOCONS = T.CDTIPOCONS), CLIENFILIAL CF, CLIENTE C, FILIAL F
						 WHERE (CF.CDCLIENTE = CO.CDCLIENTE)
							 AND (C.CDCLIENTE  = CO.CDCLIENTE)
							 AND (C.CDCLIENTE  = CF.CDCLIENTE)
							 AND (CF.CDFILIAL  = F.CDFILIAL)
							 AND (CF.CDFILIAL  = ?)
							 AND (CO.CDCLIENTE = ?)
							 AND (CF.IDPERMVENDAFOS = 'S')
							 AND (CO.IDSITCONSUMI   = '2')
							 AND (TC.IDDESABPESQCON = 'N')
							 AND (NOT EXISTS(SELECT C.CDCLIENTE
																 FROM CONSUMIDOR C
																WHERE C.CDIDCONSUMID = CO.CDIDCONSUMID
																	AND C.IDSITCONSUMI = '1'))) B
				 ORDER BY A.IDCLIENPRIN DESC, A.CDIDCONSUMID
		";

		const SQL_GET_CONSUMERS_BY_CLIENT = "
				SELECT A.CDCLIENTE,     A.CDCONSUMIDOR,  A.NMCONSUMIDOR,
							 A.VRLIMDEBCONS,  A.IDSITCONSUMI,  A.CDTIPOCONS,
							 A.CDCCUSCLIE,    A.CDIDCONSUMID,  A.VRAVIDEBCONS,
							 A.CDEXCONSUMID,  A.IDVERSALDCON,  A.IDCONSUMIDOR,
							 A.CDVENDEDOR,    A.VRMAXDEBCONS,  A.VRLIMCREDCONS,
							 A.VRMAXCREDCONS, A.VRAVICREDCONS, A.IDUTSUBTCCLI,
							 A.VRPESUBTCCLI,  A.NRRGCONSUMID,  A.NRCPFRESPCON,
							 A.NRTELECONS,    A.NRTELE2CONS,   A.IDTPVENDACONS,
							 A.NMFANTCLIE,    A.CDFILIAL, A.NMFILIAL,
							 A.IDCLIENPRIN,   A.IDIMPCPFCUPOM, A.IDCADCONFLIBCON,
							 A.DSENDECONS,    A.CDRESERVAPH,   A.DTCHECKINPH,
							 A.DTCHECKOUTPH,  TO_CHAR(A.DSOBSHOSPEDEPH) AS DSOBSHOSPEDEPH
				 FROM(
						SELECT CO.CDCLIENTE,  CO.CDCONSUMIDOR,     CO.NMCONSUMIDOR,
									 CO.VRLIMDEBCONS,  CO.IDSITCONSUMI,  CO.CDTIPOCONS,
									 CO.CDCCUSCLIE,    CO.CDIDCONSUMID,  CO.VRAVIDEBCONS,
									 CO.CDEXCONSUMID,  CO.IDVERSALDCON,  CO.IDCONSUMIDOR,
									 CO.CDVENDEDOR,    CO.VRMAXDEBCONS,  CO.VRLIMCREDCONS,
									 CO.VRMAXCREDCONS, CO.VRAVICREDCONS, CO.NRRGCONSUMID,
									 CO.NRCPFRESPCON,  CO.NRTELECONS,    CO.NRTELE2CONS,
									 T.IDUTSUBTCCLI,   T.VRPESUBTCCLI,   CO.IDTPVENDACONS,
									 C.NMFANTCLIE, F.CDFILIAL, F.NMFILIAL, CF.IDCLIENPRIN,
									 CO.IDIMPCPFCUPOM, CO.IDCADCONFLIBCON, CO.DSENDECONS,
									 CO.CDRESERVAPH, CO.DTCHECKINPH, CO.DTCHECKOUTPH,
									 CO.DSOBSHOSPEDEPH
							FROM CLIENFILIAL CF, CLIENTE C, FILIAL F,
									 CONSUMIDOR CO LEFT JOIN TIPOCONSCLI T ON (CO.CDCLIENTE  = T.CDCLIENTE)
																												AND (CO.CDTIPOCONS = T.CDTIPOCONS)
							JOIN TIPOCONS TC ON TC.CDTIPOCONS = CO.CDTIPOCONS
						 WHERE (CF.CDCLIENTE = CO.CDCLIENTE)
							 AND (C.CDCLIENTE  = CO.CDCLIENTE)
							 AND (C.CDCLIENTE  = CF.CDCLIENTE)
							 AND (CF.CDFILIAL  = F.CDFILIAL)
							 AND (CF.CDFILIAL  = ?)
							 AND (CO.CDCLIENTE = ?)
							 AND (CF.IDPERMVENDAFOS = 'S')
							 AND (CO.IDSITCONSUMI   = '1')
							 AND (TC.IDDESABPESQCON = 'N')) A
				 ORDER BY A.IDCLIENPRIN DESC, A.CDIDCONSUMID
		";

		const SQL_VERIFICA_IP_BLOQUEADO = "
				SELECT
						NRACESSOUSER
					FROM
						ACESSOFM
				 WHERE
						DSIP = ? AND
						IDACESSOUSER = 'B' AND
						DTULTATU >= SYSDATE-1
		";

		const SQL_BUSCA_IPS_BLOQUEADOS = "
				SELECT
						A.NRACESSOUSER, A.NMUSUARIO, A.DTULTATU, A.DSIP, M.NMMESA
					FROM
						ACESSOFM A, MESA M
				 WHERE
						A.NRMESA = M.NRMESA AND
						M.CDFILIAL = ? AND
						A.IDACESSOUSER = 'B' AND
						A.DTULTATU >= SYSDATE-1
		";

		const SQL_LISTA_COMANDA = "
			 SELECT C.DSCOMANDA, C.NRVENDAREST, C.NRCOMANDA,
							O.NMCONSUMIDOR,
							C.DSCOMANDA || (CASE WHEN NVL(C.DSCONSUMIDOR, O.NMCONSUMIDOR) IS NULL THEN '' ELSE ' - ' END) ||
							NVL(NVL(C.DSCONSUMIDOR, O.NMCONSUMIDOR), '') AS LABELDSCOMANDA
				 FROM COMANDAVEN C JOIN VENDAREST V
														 ON C.CDFILIAL = V.CDFILIAL
														AND C.CDLOJA = V.CDLOJA
														AND C.NRVENDAREST = V.NRVENDAREST
											LEFT JOIN CONSUMIDOR O
														 ON V.CDCLIENTE = O.CDCLIENTE
														AND V.CDCONSUMIDOR = O.CDCONSUMIDOR
				WHERE C.CDFILIAL = ?
					AND C.CDLOJA = ?
					AND (SUBSTR(C.DSCOMANDA,1,4) <> 'RES_')
					AND (SUBSTR(C.DSCOMANDA,1,4) <> 'PKR_')
					AND (SUBSTR(C.DSCOMANDA,1,4) <> 'DLV_')
					AND C.IDSTCOMANDA <> '4'
					AND C.IDSTCOMANDA <> '7'
				ORDER BY C.DSCOMANDA
		";

		const SQL_CONSULTA_MESA = "
				SELECT B.CDFILIAL, B.NRMESA, B.NMMESA, B.CDSALA,
							 B.NMSALA, B.IDSTMESAAUX, B.IDCONTROLE, B.TEMPOCOMSUMIR,
							 B.NRPESMESAVEN, B.NRPOSICAOMESA, B.NMVENDEDORABERT
					FROM (SELECT MS.CDFILIAL, MS.NRMESA, MS.NMMESA, SL.CDSALA,
											 IT.DSBUTTON AS NMSALA, MS.IDSTMESAAUX, 'R' AS IDCONTROLE, ' ' AS TEMPOCOMSUMIR,
											 '0' AS NRPESMESAVEN, '0' AS NRPOSICAOMESA,
											 NULL AS NMVENDEDORABERT
									FROM MESA MS, MESARESERVA RV, RESERVAMESA RM, SALA SL,
											 ITMENUCONFTE IT
								 WHERE MS.CDFILIAL     = ?
									 AND MS.CDLOJA       = ?
									 AND MS.CDFILIAL     = RV.CDFILIAL
									 AND MS.CDLOJA       = RV.CDLOJA
									 AND MS.NRMESA       = RV.NRMESA
									 AND RV.CDFILIAL     = RM.CDFILIAL
									 AND RV.CDLOJA       = RM.CDLOJA
									 AND RV.NRRESMESA    = RM.NRRESMESA
									 AND RM.IDSTRESMESA  = 'P'
									 AND MS.CDFILIAL     = SL.CDFILIAL
									 AND MS.CDSALA       = SL.CDSALA
									 AND MS.CDFILIAL     = IT.CDFILIAL
									 AND IT.NRCONFTELA   = ?
									 AND IT.CDIDENTBUTON = SL.CDSALA
									 AND IT.IDTPBUTTON   = '4'
									 AND (TO_CHAR(RM.DTRESMESA, 'DD/MM/YYYY') = TO_CHAR(SYSDATE,'HH24:MI:SS'))
									 AND MS.NRMESA IN (SELECT CDIDENTBUTON
																			 FROM ITMENUCONFTE
																			WHERE CDFILIAL   = ?
																				AND NRCONFTELA = ?
																				AND IDTPBUTTON = '3')

								UNION

								SELECT MS.CDFILIAL, MS.NRMESA, MS.NMMESA, SL.CDSALA,
											 IT.DSBUTTON AS NMSALA, MS.IDSTMESAAUX, 'N' AS IDCONTROLE, ' ' AS TEMPOCOMSUMIR,
											 NVL(VR.NRPESMESAVEN, '0') AS NRPESMESAVEN, NVL(VR.NRPOSICAOMESA, '0') AS NRPOSICAOMESA,
											 VD.NMFANVEN AS NMVENDEDORABERT
									FROM SALA SL, ITMENUCONFTE IT, MESA MS LEFT JOIN VENDAREST VR
																							 ON MS.CDFILIAL = VR.CDFILIAL
																							AND MS.CDLOJA   = VR.CDLOJA
																							AND MS.NRMESA   = VR.NRMESA
									LEFT JOIN VENDEDOR VD
										ON VR.CDVENDEDOR = VD.CDVENDEDOR
								 WHERE MS.CDFILIAL     = ?
									 AND MS.CDLOJA       = ?
									 AND MS.CDFILIAL     = SL.CDFILIAL
									 AND MS.CDSALA       = SL.CDSALA
									 AND MS.CDFILIAL     = IT.CDFILIAL
									 AND IT.NRCONFTELA   = ?
									 AND IT.CDIDENTBUTON = SL.CDSALA
									 AND IT.IDTPBUTTON   = '4'
									 AND MS.NRMESA IN (SELECT CDIDENTBUTON
																			 FROM ITMENUCONFTE
																			WHERE CDFILIAL   = ?
																				AND NRCONFTELA = ?
																				AND IDTPBUTTON = '3')
									 AND MS.NRMESA NOT IN (SELECT NVL(NRMESAPADRAO, '')
																					 FROM LOJA
																					WHERE CDFILIAL = ?
																						AND CDLOJA = ?)
									 AND MS.NRMESA NOT IN (SELECT RV.NRMESA
																					 FROM MESARESERVA RV, RESERVAMESA RM
																					WHERE RV.CDFILIAL    = ?
																						AND RV.CDLOJA      = ?
																						AND RV.CDFILIAL    = RM.CDFILIAL
																						AND RV.CDLOJA      = RM.CDLOJA
																						AND RV.NRRESMESA   = RM.NRRESMESA
																						AND RM.IDSTRESMESA = 'P'
																						AND (TO_CHAR(RM.DTRESMESA, 'HH24:MI:SS') = TO_CHAR(SYSDATE, 'HH24:MI:SS')))) B
		";

		const SQL_DATA_ABERTURA = "
				SELECT TO_CHAR(DTHRABERMESA, 'YYYY-MM-DD HH24:MI:SS') AS DTABERTMESA
					FROM VENDAREST
				 WHERE CDFILIAL = ?
					 AND CDLOJA   = ?
					 AND NRMESA   = ?
					 AND TO_CHAR(DTHRFECHMESA, 'DD/MM/YYYY') IS NULL
		";

		const GET_TABLES_WITH_DELAYED_ITEMS = "
				SELECT DISTINCT R.NRMESA
					FROM ITPEDIDOFOSREL IR JOIN ITPEDIDOFOS I
																	 ON IR.CDFILIAL = I.CDFILIAL
																	AND IR.NRPEDIDOFOS = I.NRPEDIDOFOS
																	AND IR.NRITPEDIDOFOS = I.NRITPEDIDOFOS

																 JOIN SETOR S
																	ON I.CDSETOR = S.CDSETOR

																JOIN PRODUTO P
																	ON I.CDPRODUTO = P.CDPRODUTO

																JOIN ITCOMANDAVEN T
																	ON IR.CDFILIAL = T.CDFILIAL
																 AND IR.NRVENDAREST = T.NRVENDAREST
																 AND IR.NRCOMANDA = T.NRCOMANDA
																 AND IR.NRPRODCOMVEN = T.NRPRODCOMVEN

																JOIN VENDAREST R
																	ON IR.CDFILIAL = R.CDFILIAL
																 AND IR.NRVENDAREST = R.NRVENDAREST

				 WHERE S.IDTIPOSETOR = 'E'
					 AND I.IDLIBERADO = 'N'
					 AND T.NRATRAPRODCOVE IS NOT NULL
					 AND I.NRATRAPRODITPE IS NOT NULL
					 AND I.DTHREXIBICAOPROD > SYSDATE
					 AND T.CDFILIAL = :CDFILIAL
					 AND T.IDSTPRCOMVEN <> '6'

				UNION

				SELECT DISTINCT R.NRMESA
					FROM ITPEDIDOFOSREL IR JOIN ITPEDIDOFOS I
																	 ON IR.CDFILIAL = I.CDFILIAL
																	AND IR.NRPEDIDOFOS = I.NRPEDIDOFOS
																	AND IR.NRITPEDIDOFOS = I.NRITPEDIDOFOS

																 JOIN SETOR S
																	 ON I.CDSETOR = S.CDSETOR

																 JOIN PRODUTO P
																	 ON I.CDPRODUTO = P.CDPRODUTO

																 JOIN ITCOMANDAEST T
																	 ON IR.CDFILIAL = T.CDFILIAL
																	AND IR.NRVENDAREST = T.NRVENDAREST
																	AND IR.NRCOMANDA = T.NRCOMANDA
																	AND IR.NRPRODCOMVEN = T.NRPRODCOMVEN
																	AND I.CDPRODUTO = T.CDPRODUTO

																 JOIN ITCOMANDAVEN V
																	 ON IR.CDFILIAL = V.CDFILIAL
																	AND IR.NRVENDAREST = V.NRVENDAREST
																	AND IR.NRCOMANDA = V.NRCOMANDA
																	AND IR.NRPRODCOMVEN = V.NRPRODCOMVEN

																 JOIN VENDAREST R
																	 ON IR.CDFILIAL = R.CDFILIAL
																	AND IR.NRVENDAREST = R.NRVENDAREST

				 WHERE S.IDTIPOSETOR = 'E'
					 AND I.IDLIBERADO = 'N'
					 AND T.NRATRAPRODCOES IS NOT NULL
					 AND I.NRATRAPRODITPE IS NOT NULL
					 AND I.DTHREXIBICAOPROD > SYSDATE
					 AND T.CDFILIAL = :CDFILIAL
					 AND V.IDSTPRCOMVEN <> '6'
		";

		const BUSCA_MESAS_AGRUPADAS = "
				SELECT V.NRVENDAREST, C.NRCOMANDA, V.NRMESA, V.NRPESMESAVEN, NVL(CO.IDSEXOCONS, 'M') AS IDSEXOCONS, MS.IDSTMESAAUX, V.NRPOSICAOMESA
					FROM MESAJUNCAO MJ, COMANDAVEN C, MESA MS, VENDAREST V
					LEFT JOIN CONSUMIDOR CO
								 ON V.CDCONSUMIDOR = CO.CDCONSUMIDOR
								AND V.CDCLIENTE = CO.CDCLIENTE
				 WHERE MJ.NRJUNMESA = (SELECT NRJUNMESA
																 FROM MESAJUNCAO
																WHERE CDFILIAL = :CDFILIAL
																	AND CDLOJA = :CDLOJA
																	AND NRMESA = :NRMESA)
					 AND V.NRVENDAREST = C.NRVENDAREST
					 AND V.NRMESA = MJ.NRMESA
					 AND MS.NRMESA = V.NRMESA
					 AND MS.CDFILIAL = V.CDFILIAL
					 AND MS.CDLOJA = V.CDLOJA

				 UNION

				SELECT V.NRVENDAREST, C.NRCOMANDA, V.NRMESA, V.NRPESMESAVEN, NVL(CO.IDSEXOCONS, 'M') AS IDSEXOCONS, MS.IDSTMESAAUX, V.NRPOSICAOMESA
					FROM COMANDAVEN C, MESA MS, VENDAREST V
					LEFT JOIN CONSUMIDOR CO
								 ON V.CDCONSUMIDOR = CO.CDCONSUMIDOR
								AND V.CDCLIENTE = CO.CDCLIENTE
				 WHERE V.NRVENDAREST = C.NRVENDAREST
					 AND V.NRMESA NOT IN (SELECT NRMESA
																	FROM MESAJUNCAO)
					 AND V.CDFILIAL = :CDFILIAL
					 AND V.CDLOJA = :CDLOJA
					 AND V.NRMESA = :NRMESA
					 AND MS.NRMESA = V.NRMESA
					 AND MS.CDFILIAL = V.CDFILIAL
					 AND MS.CDLOJA = V.CDLOJA
		";

		const SQL_ITENS_DETALHADOS = "
				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT. NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN, 'HH24:MI:SS') AS HORA, IT.IDDIVIDECONTA,
					IT.NRPRODORIG, V.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND ((INSTR(?, IT.NRLUGARMESA) > 0)  or ('T' = ?))
					AND IT.CDPRODPROMOCAO IS NULL
					AND IT.IDPRODREFIL = 'N'
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON,TO_CHAR(IT.DTHRINCOMVEN, 'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.IDDIVIDECONTA, IT.NRPRODORIG, V.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA

				UNION

				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST,
					IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO,
					IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA, IT.IDDIVIDECONTA,
					IT.NRPRODORIG, V.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'S')
					AND ((INSTR(?, IT.NRLUGARMESA) > 0)  or ('T' = ?))
					AND ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
					AND IT.CDPRODPROMOCAO IS NULL
					AND IT.IDPRODREFIL = 'N'
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON, TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.IDDIVIDECONTA, IT.NRPRODORIG, V.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA

				UNION

				SELECT
					NVL(IM.DSBUTTON, PR.NMPRODUTO) AS DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN,
					IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODPROMOCAO AS CDPRODUTO, '3' AS IDSTPRCOMVEN,
					NULL AS NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) AS TXPRODCOMVEN, PR.IDCOBTXSERV, NVL(IT.NRLUGARMESA, '01') AS NRLUGARMESA,
					VE.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS, IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO,
					'PROMO' AS GRUPO, TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA, IT.IDDIVIDECONTA,
					IT.NRPRODORIG, VE.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
				FROM
					PRODUTO PR, VENDAREST VE, ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM ON IM.CDIDENTBUTON = IT.CDPRODUTO
				WHERE IT.CDFILIAL = ?
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND IT.CDPRODPROMOCAO IS NOT NULL
					AND IT.CDPRODUTO = PR.CDPRODUTO
					AND ((INSTR(?, IT.NRLUGARMESA) > 0)  or ('T' = ?))
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND IT.CDFILIAL = VE.CDFILIAL
					AND IT.NRVENDAREST = VE.NRVENDAREST
					AND IT.IDPRODREFIL = 'N'
				GROUP BY
					IM.DSBUTTON, PR.NMPRODUTO, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					IT.QTPRODCOMVEN, IT.VRPRECCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN,
					PR.CDARVPROD, IT.CDPRODPROMOCAO, TO_CHAR(IT.TXPRODCOMVEN), PR.IDCOBTXSERV, IT.NRLUGARMESA,
					VE.DTHRABERMESA, PR.CDBARPRODUTO, IT.NRSEQPRODCOM, IT.NRSEQPRODCUP,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'), TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.IDDIVIDECONTA,
					IT.NRPRODORIG, VE.NRMESA, IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
		";

		const SQL_ITENS_ITCOMANDAEST = "
				SELECT NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO) AS DSBUTTON, IT.NRPRODCOMVEN,
							 IT.CDPRODUTO, IT.QTPROCOMEST AS QUANT, NULL AS PRECO, IT.VRDESITCOMEST AS DESCONTO,
							 'E' AS TIPOPROMO, '' AS LISTA, IT.TXPRODCOMVENEST AS TXPRODCOMVEN
					FROM ITCOMANDAEST IT, PRODUTO PR
				 WHERE IT.CDFILIAL = ?
					 AND IT.NRVENDAREST = ?
					 AND IT.NRCOMANDA = ?
					 AND IT.NRPRODCOMVEN = ?
					 AND PR.CDPRODUTO = IT.CDPRODUTO
		";

		const SQL_UPDATE_MOVCAIXAMOB = "
				UPDATE MOVCAIXAMOB
					 SET DTHRFIMMOV = SYSDATE,
							 NRSEQMOB = :NRSEQMOB,
							 NRADMCODE = :NRADMCODE,
							 IDADMTASK = :IDADMTASK,
							 IDSTMOV = :IDSTMOV,
							 TXMOVUSUARIO = :TXMOVUSUARIO,
							 TXMOVJSON = :TXMOVJSON,
							 CDNSUTEFMOB = :CDNSUTEFMOB,
							 TXPRIMVIATEF = REPLACE(CAST(:TXPRIMVIATEF AS VARCHAR2(MAX)), '\r\n', CHAR(10)),
							 TXSEGVIATEF = REPLACE(CAST(:TXSEGVIATEF AS VARCHAR2(MAX)), '\r\n', CHAR(10))
				 WHERE NRSEQMOVMOB = :NRSEQMOVMOB
		";

		const SQL_INSERT_MOVCAIXAMOB = "
				INSERT INTO MOVCAIXAMOB(
						CDFILIAL, CDCAIXA, CDVENDEDOR, NRVENDAREST, NRCOMANDA, NRSEQVENDA, NRMESA, NRLUGARMESA, NRSEQMOVMOB, DTHRINCMOV,
						VRMOV, IDTIPMOV, DSBANDEIRA, NRADMCODE, IDADMTASK, NRORG, IDATIVO, DTINCLUSAO, NRORGINCLUSAO, CDOPERINCLUSAO,
						CDTIPORECE, CDNSUTEFMOB, TXPRIMVIATEF, TXSEGVIATEF, IDTPTEF, CDCLIENTE, CDCONSUMIDOR, IDSTMOV)
				VALUES
					 (:CDFILIAL, :CDCAIXA, :CDVENDEDOR, :NRVENDAREST, :NRCOMANDA, :NRSEQVENDA, :NRMESA, :NRLUGARMESA, :NRSEQMOVMOB, :DTHRINCMOV,
						:VRMOV, :IDTIPMOV, :DSBANDEIRA, :NRADMCODE, :IDADMTASK, :NRORG, :IDATIVO, :DTINCLUSAO, :NRORGINCLUSAO, :CDOPERINCLUSAO,
						:CDTIPORECE, :CDNSUTEFMOB, :TXPRIMVIATEF, :TXSEGVIATEF, :IDTPTEF, :CDCLIENTE, :CDCONSUMIDOR, :IDSTMOV)
		";

		const SQL_GET_MAIN_PRODUCT = "
				SELECT I.CDFILIAL, I.NRPEDIDOFOS, I.NRITPEDIDOFOS, NVL(I.NRTEMPOPRODIT, 0) AS NRTEMPOPRODIT,
							 I.NRATRAPRODITPE, I.DTHREXIBICAOPROD AS DTHREXIBATRASO, S.IDTIPOSETOR
					FROM ITPEDIDOFOS I JOIN SETOR S
															 ON I.CDSETOR = S.CDSETOR
				 WHERE I.CDFILIAL = ?
					 AND I.NRPEDIDOFOS = ?
					 AND I.NRITPEDIDOFOS = ?
		";

		const SQL_GET_PRODUCT_COMPOSITION = "
				SELECT I.CDFILIAL, I.NRPEDIDOFOS, I.NRITPEDIDOFOS, NVL(I.NRTEMPOPRODIT, 0) AS NRTEMPOPRODIT,
							 I.NRATRAPRODITPE, I.DTHREXIBICAOPROD AS DTHREXIBATRASO, S.IDTIPOSETOR
					FROM ITPEDIDOFOSPAI P JOIN ITPEDIDOFOS I
																	ON P.CDFILIAL = I.CDFILIAL
																 AND P.NRPEDIDOFOS = I.NRPEDIDOFOS
																 AND P.NRITPEDIDOFOS = I.NRITPEDIDOFOS
																JOIN SETOR S
																	ON I.CDSETOR = S.CDSETOR
				 WHERE P.CDFILIALPAI = ?
					 AND P.NRPEDIDOFOSPAI = ?
					 AND P.NRITPEDIDOFOSPAI = ?
		";

		const SQL_ACESSOS = "
				SELECT AF.NRACESSOUSER, AF.NRMESA, AF.NMUSUARIO, AF.IDACESSOUSER,
							 '' AS VAZIO, ME.NMMESA, (AF.NMUSUARIO || ' na mesa ') AS USERMESA,
							 TRUNC((AF.DTULTATU - SYSDATE) * 60 * 60 * 24) AS TEMPO
					FROM ACESSOFM AF, MESA ME
				 WHERE AF.NRMESA = ME.NRMESA
				 AND AF.IDACESSOUSER = 'P'
		";

		const SQL_ACESSOS_AUT = "
				SELECT AF.NRACESSOUSER, AF.NRMESA, AF.NMUSUARIO, AF.IDACESSOUSER,
							 '' AS VAZIO, ME.NMMESA, (AF.NMUSUARIO || ' na mesa ' || ME.NMMESA) AS USERMESA,
							 TRUNC((AF.DTULTATU - SYSDATE) * 60 * 60 * 24) AS TEMPO
					FROM ACESSOFM AF, MESA ME
				 WHERE AF.NRMESA = ME.NRMESA
				 AND AF.IDACESSOUSER = 'A'
		";

		const SQL_DADOS_CAIXA = "
				SELECT CX.CDFILIAL, CX.CDCAIXA, CX.CDLOJA, CX.NRCONFTELA, CX.IDLEITURAQRCODE,
							 LJ.IDCOMANDAVEN, LJ.IDCOMISVENDA, LJ.VRCOMISVENDA, LJ.NRMESAPADRAO, LJ.IDINFVENDCOM,
							 LJ.IDUTIVENDPAD, LJ.CDVENDPADRAO, LJ.IDCOUVERART, LJ.CDPRODCONSUM, LJ.CDPRODCONSUF,
							 LJ.IDRATEIOCOMI, LJ.CDCLIENTERAT, LJ.NRMINSEMCONS, LJ.CDPRODCOUVER,
							 LJ.IDCONSUMAMIN, LJ.IDLUGARMESA, LJ.IDCONTROPROD, LJ.CDPRODCOMVEN,
							 LJ.IDSOLOBSPED, LJ.IDSOLOBSCAN, LJ.CDGRPOCORCAN, LJ.CDGRPOCORPED,
							 CX.IDDIGCODPLM, LJ.NMLOJA, LJ.IDINFMESACOM, CX.IDPERABERCOMCXA,
							 CX.IDTIPOIMPNF, LJ.IDCOMANDAAUT, LJ.IDINFCONSCOM, LJ.IDUTLSENHAOPER,
							 LJ.IDPOSOBSPED, CX.CDPORTAIMPNF, CX.CDPORTAIMPNF2, CX.IDTIPOIMPNF2,
							 CX.NRSEQIMPRLOJA1, CX.NRSEQIMPRLOJA2, LJ.IDBLOQCOMPARC, CX.IDTPTEF,
							 NVL(CX.CDFILICONFTE, CX.CDFILIAL) AS CDFILICONFTE, CX.IDCOLETOR,
							 CX.NRORG, CX.IDTPEMISSAOFOS, CX.IDUTILTEF, CX.IDPALFUTRABRCXA,
							 TO_NUMBER(CX.VRABERCAIX) AS VRABERCAIX,  CX.IDHABCAIXAVENDA, LJ.IDTIPCOBRA,
							 IM.IDMODEIMPRES, CX.CDTERTEF, CX.CDLOJATEF, CX.DSENDIPSITEF, CX.IDSOLDIGCONS,
							 LJ.IDUTLNMCONSMESA, LJ.IDAGRUPAPEDCOM, CX.IDTPTELAVE, CX.IDSOLICITACPF,
							 CX.IDLCDBARBALATOL, CX.NRPOSINICODBARR, CX.NRPOSFINCODBARR, LJ.VRCOMISVENDA2,
							 LJ.VRCOMISVENDA3, CX.IDPERCOMVENCPDC, LJ.IDSOLOBSDESC, CX.IDSOLTPSANGRIACX,
							 CX.IDCAIXAEXCLUSIVO, LJ.IDSOLOBSFINVEN,LJ.IDMOSTRADESPARC, LJ.VRMAXDESCONTO,
							 LJ.IDSOLOBSCAN, CX.IDIMPPEDPROD, CX.IDSINCCAIXADLV, CX.IDUTCXDRIVETHU,
							 CX.IDSENHACUP
					FROM LOJA LJ,
							 CAIXA CX LEFT JOIN IMPRLOJA IL
															 ON CX.CDFILIAL = IL.CDFILIAL
															AND CX.CDLOJA = IL.CDLOJA
															AND CX.NRSEQIMPRLOJA3 = IL.NRSEQIMPRLOJA
												LEFT JOIN IMPRESSORA IM
															 ON IL.CDIMPRESSORA = IM.CDIMPRESSORA
				 WHERE CX.CDFILIAL = ?
					 AND CX.CDCAIXA  = ?
					 AND CX.CDFILIAL = LJ.CDFILIAL
					 AND CX.CDLOJA   = LJ.CDLOJA
		";

		const SQL_BD_VERSION = '
				SELECT * FROM V$VERSION
		';

		const SQL_TEMPO_PERMANENCIA = "
				SELECT TO_CHAR(VE.DTHRABERMESA, 'YYYY-MM-DD HH24:MI:SS')||'.000' AS DATA
					FROM VENDAREST VE, COMANDAVEN CM
					WHERE CM.CDFILIAL    = ?
						AND CM.NRVENDAREST = ?
						AND CM.NRCOMANDA   = ?
						AND VE.CDFILIAL    = CM.CDFILIAL
						AND VE.NRVENDAREST = CM.NRVENDAREST
		";

		const SQL_PRODUTOS_PARCIAL = "
				SELECT IT.NRVENDAREST, IT.NRCOMANDA, MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN,
							 SUM(IT.VRDESCCOMVEN) AS VRDESCCOMVEN, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO) AS NMPRODUTO,
							 IT.VRPRECCOMVEN, IT.VRPRECCLCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT,
							 SUM(VRACRCOMVEN) AS VRACRCOMVEN, PR.IDCOBTXSERV, NVL(IT.NRLUGARMESA, '001') AS NRLUGARMESA, V.DTHRABERMESA,
							 PR.CDBARPRODUTO AS CDPRODIMPFIS, NVL(VE.VRPERCCOMISVEND, 0) AS VRPERCCOMISVEND, VE.IDVRINCIDECONTA,
							 SUM((IT.VRPRECCOMVEN - IT.VRDESCCOMVEN + IT.VRACRCOMVEN) * IT.QTPRODCOMVEN) AS PRECO, PR.IDPESAPROD,
                             IT.CDPRODPROMOCAO, IT.NRSEQPRODCOM, IT.IDDESCMANUAL
					FROM ITCOMANDAVEN IT
					JOIN PRODUTO PR ON PR.CDPRODUTO = IT.CDPRODUTO
					JOIN VENDAREST V ON V.CDFILIAL = IT.CDFILIAL
													AND V.NRVENDAREST = IT.NRVENDAREST
					LEFT JOIN VENDEDOR VE ON VE.CDVENDEDOR = IT.CDVENDEDOR
				 WHERE (IT.CDFILIAL = ?)
					 AND (INSTR(?, IT.NRCOMANDA) > 0)
					 AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) OR ('T' = 'X'))
					 AND (IT.CDPRODUTO <> 'X')
					 AND (PR.IDPESAPROD = 'N')
					 AND ((INSTR(?, IT.NRLUGARMESA) > 0) or ('T' = ?))
					 AND IT.IDPRODREFIL = 'N'
				 GROUP BY IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO), IT.VRPRECCOMVEN, IT.VRPRECCLCOMVEN,
									PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, PR.IDCOBTXSERV,
									IT.NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN,
									IT.VRDESCCOMVEN, IT.VRACRCOMVEN, VRPERCCOMISVEND, VE.IDVRINCIDECONTA, PR.IDPESAPROD,
                                    IT.CDPRODPROMOCAO, IT.NRSEQPRODCOM, IT.IDDESCMANUAL
				 UNION
				SELECT IT.NRVENDAREST, IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN,
							 IT.VRDESCCOMVEN AS VRDESCCOMVEN, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO) AS NMPRODUTO,
							 IT.VRPRECCOMVEN, IT.VRPRECCLCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT,
							 VRACRCOMVEN AS VRACRCOMVEN, PR.IDCOBTXSERV, NVL(IT.NRLUGARMESA, '001') AS NRLUGARMESA, V.DTHRABERMESA,
							 PR.CDBARPRODUTO AS CDPRODIMPFIS, NVL(VE.VRPERCCOMISVEND, 0) AS VRPERCCOMISVEND, VE.IDVRINCIDECONTA,
							 SUM((IT.VRPRECCOMVEN - IT.VRDESCCOMVEN + IT.VRACRCOMVEN) * IT.QTPRODCOMVEN) AS PRECO, PR.IDPESAPROD,
                             IT.CDPRODPROMOCAO, IT.NRSEQPRODCOM, IT.IDDESCMANUAL
					FROM ITCOMANDAVEN IT
					JOIN PRODUTO PR ON PR.CDPRODUTO = IT.CDPRODUTO
					JOIN VENDAREST V ON V.CDFILIAL = IT.CDFILIAL
													AND V.NRVENDAREST = IT.NRVENDAREST
					LEFT JOIN VENDEDOR VE ON VE.CDVENDEDOR = IT.CDVENDEDOR
				 WHERE (IT.CDFILIAL = ?)
					 AND (INSTR(?, IT.NRCOMANDA) > 0)
					 AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) OR ('T' = 'X'))
					 AND (IT.CDPRODUTO <> 'X')
					 AND (PR.IDPESAPROD = 'S')
					 AND ((INSTR(?, IT.NRLUGARMESA) > 0) or ('T' = ?))
					 AND IT.IDPRODREFIL = 'N'
				 GROUP BY IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO), IT.VRPRECCOMVEN, IT.VRPRECCLCOMVEN,
									PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, PR.IDCOBTXSERV,
									IT.NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN,
									IT.VRDESCCOMVEN, IT.VRACRCOMVEN, VRPERCCOMISVEND, VE.IDVRINCIDECONTA, PR.IDPESAPROD,
                                    IT.CDPRODPROMOCAO, IT.NRSEQPRODCOM, IT.IDDESCMANUAL
				 ORDER BY NRLUGARMESA, NRVENDAREST, NRCOMANDA, NRPRODCOMVEN, QTPRODCOMVEN,
									VRDESCCOMVEN, NMPRODUTO, VRPRECCOMVEN, CDARVPROD, CDPRODUTO, IDSTPRCOMVEN,
									NRMESADSCOMORIT, VRACRCOMVEN, IDCOBTXSERV, DTHRABERMESA, CDPRODIMPFIS, PRECO
		";

		const SQL_PRODUTOS_PARCIAL_NUMERO_PRODUTOS = "
				SELECT COUNT(NRPRODCOMVEN) AS NRITENS
					FROM ITCOMANDAVEN
				 WHERE CDFILIAL = ?
					 AND (INSTR(?, NRVENDAREST) > 0)
					 AND (INSTR(?, NRCOMANDA) > 0)
					 AND ((INSTR(?, NRLUGARMESA) > 0)  OR ('T' = ?))
					 AND IDSTPRCOMVEN NOT IN ('6', '7')
		";

		const SQL_POSICAO_PARCIAL = "
				SELECT A.NRLUGARMESA, SUM(A.PRECOTX) AS PRECOTX, SUM(A.PRECONTX) AS PRECONTX
					FROM (
						SELECT I.NRLUGARMESA, SUM(TRUNC((I.VRPRECCOMVEN + I.VRPRECCLCOMVEN) * I.QTPRODCOMVEN, 2) + I.VRACRCOMVEN - I.VRDESCCOMVEN) AS PRECOTX, 0 AS PRECONTX
							FROM ITCOMANDAVEN I, PRODUTO P
							WHERE I.CDPRODUTO   = P.CDPRODUTO
								AND I.CDFILIAL    = :CDFILIAL
								AND (INSTR(:NRVENDAREST, I.NRVENDAREST) > 0)
								AND (INSTR(:NRCOMANDA, I.NRCOMANDA) > 0)
								AND I.IDSTPRCOMVEN NOT IN ('6','7')
								AND ((I.CDPRODUTO <> :CDPRODUTO) OR (:CDPRODUTO IS NULL))
								AND P.IDCOBTXSERV = 'S'
						GROUP BY I.NRLUGARMESA
						UNION ALL
						SELECT I.NRLUGARMESA, 0 AS PRECOTX, SUM(TRUNC((I.VRPRECCOMVEN + I.VRPRECCLCOMVEN) * I.QTPRODCOMVEN, 2) + I.VRACRCOMVEN - I.VRDESCCOMVEN) AS PRECONTX
							FROM ITCOMANDAVEN I, PRODUTO P
							WHERE I.CDPRODUTO   = P.CDPRODUTO
								AND I.CDFILIAL    = :CDFILIAL
								AND (INSTR(:NRVENDAREST, I.NRVENDAREST) > 0)
								AND (INSTR(:NRCOMANDA, I.NRCOMANDA) > 0)
								AND I.IDSTPRCOMVEN NOT IN ('6','7')
								AND ((I.CDPRODUTO <> :CDPRODUTO) OR (:CDPRODUTO IS NULL))
								AND P.IDCOBTXSERV = 'N'
						GROUP BY I.NRLUGARMESA
				) A
				GROUP BY A.NRLUGARMESA
		";

		const SQL_ITENS_DETALHADOS_SEM_COMBO = "
				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT. NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA,
					IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND ((INSTR(?, NRLUGARMESA) > 0) or ('T' = ?))
					AND IT.CDPRODPROMOCAO IS NULL
					AND IT.IDDIVIDECONTA = 'N'
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON,TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA

				UNION

				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST,
					IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO,
					IT.IDSTPRCOMVEN, IT.NRMESADSCOMORIT, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA,
					IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCOMANDAVEN IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE (IT.CDFILIAL = ?)
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'S')
					AND ((INSTR(?, NRLUGARMESA) > 0) or ('T' = ?))
					AND ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
					AND IT.CDPRODPROMOCAO IS NULL
					AND IT.IDDIVIDECONTA = 'N'
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					IT.NRMESADSCOMORIT, PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON, TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS'), IT.VRPRECCLCOMVEN, IT.IDORIGEMVENDA
		";

		const SQL_ITENS_ORIGINAIS = "
				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA,
					MIN(IT.NRPRODCOMVEN) AS NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT. NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCMDVENORIG IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE IT.CDFILIAL         = ?
						AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON,TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS')

				UNION

				SELECT
					NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO)) DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST,
					IT.NRCOMANDA, IT.NRPRODCOMVEN AS NRPRODCOMVEN, IT.QTPRODCOMVEN AS QTPRODCOMVEN, IT.VRDESCCOMVEN AS VRDESCCOMVEN,
					IT.VRACRCOMVEN AS VRACRCOMVEN, IT.VRPRECCOMVEN AS VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO,
					IT.IDSTPRCOMVEN, TO_CHAR(IT.TXPRODCOMVEN) TXPRODCOMVEN, PR.IDCOBTXSERV,
					NVL(IT.NRLUGARMESA,'001') AS NRLUGARMESA, V.DTHRABERMESA, PR.CDBARPRODUTO AS CDPRODIMPFIS,
					IT.NRSEQPRODCOM, IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, GROUPS.DSBUTTON AS GRUPO,
					TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY') AS DATA, TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS') AS HORA
				FROM
					PRODUTO PR, VENDAREST V,
					ITCMDVENORIG IT LEFT JOIN ITMENUCONFTE IM
								 ON (IT.CDPRODUTO = IM.CDIDENTBUTON
										AND IT.CDFILIAL = IM.CDFILIAL
								AND IM.NRCONFTELA = ?
								AND IM.IDTPBUTTON = '1')
													LEFT JOIN (SELECT DSBUTTON, (NRPGCONFTELA + NRBUTTON) AS CDGRUPO
																			 FROM ITMENUCONFTE
																			WHERE IDTPBUTTON = '2'
																				AND CDFILIAL = ?
																				AND NRCONFTELA = ?) GROUPS
																 ON ((IM.NRPGCONFTAUX + IM.NRBUTTONAUX) = GROUPS.CDGRUPO)
				WHERE IT.CDFILIAL       = ?
					AND (INSTR(?, IT.NRCOMANDA) > 0)
					AND (IT.CDPRODUTO = PR.CDPRODUTO)
					AND ((IT.IDSTPRCOMVEN NOT IN ('6','7')) or ('T' = 'X'))
					AND (IT.CDPRODUTO <> 'X')
					AND (IT.CDFILIAL    = V.CDFILIAL)
					AND (IT.NRVENDAREST = V.NRVENDAREST)
					AND (PR.IDPESAPROD = 'N')
					AND IT.CDPRODPROMOCAO IS NULL
				GROUP BY
					IM.DSBUTTON, IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
					IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT.VRPRECCOMVEN, PR.CDARVPROD, IT.CDPRODUTO, IT.IDSTPRCOMVEN,
					PR.IDCOBTXSERV, IT.NRLUGARMESA , V.DTHRABERMESA, TO_CHAR(IT.TXPRODCOMVEN),
					PR.CDBARPRODUTO, IT.NRPRODCOMVEN, IT.QTPRODCOMVEN, IT.VRDESCCOMVEN, IT.VRACRCOMVEN, IT. NRSEQPRODCOM,
					IT.NRSEQPRODCUP, IT.CDPRODPROMOCAO, IM.NRBUTTON, GROUPS.DSBUTTON, TO_CHAR(IT.DTHRINCOMVEN,'DD/MM/YYYY'),
					TO_CHAR(IT.DTHRINCOMVEN,'HH24:MI:SS')
		";

		const SQL_INSERE_ACESSO = "
				INSERT INTO
						ACESSOFM
							 (NRACESSOUSER, NRMESA, NMUSUARIO, DSIP, DTULTATU)
							VALUES
							 (?, ?, ?, ?, SYSDATE)
		";

		const SQL_UPDATE_ACESSO = "
				UPDATE ACESSOFM
					SET IDACESSOUSER = 'P',
							DTULTATU = SYSDATE
				WHERE NRACESSOUSER = ?
				 AND NRMESA = ?
				 AND NMUSUARIO = ?
		";

		const TABELA_VENDA = "
				SELECT TO_CHAR(DTINIVGPREC,'YYYY-MM-DD HH24:MI:SS') AS DTINIVGPREC
					FROM TABEVEND
				 WHERE CDFILIAL   = ?
					 AND CDTABEPREC = ?
					 AND (TO_CHAR(SYSDATE, 'DD/MM/YYYY') BETWEEN DTINIVGPREC AND DTFINVGPREC)
		";

		const SQL_MOVER_TRANSACOES = "
				UPDATE MOVCAIXAMOB
				SET NRLUGARMESA = ?
				WHERE CDFILIAL = ?
					AND (INSTR(?, NRVENDAREST) > 0)
					AND (INSTR(?, NRLUGARMESA) > 0)
					AND IDSTMOV = 1
					AND IDADMTASK = 0
		";

		const SQL_BUSCA_TRANSACOES_TEMPO = "
				SELECT *
					FROM (
						SELECT D.*, ROW_NUMBER() OVER (ORDER BY DTHRFIMMOV DESC) AS N FROM (
										SELECT TO_CHAR(M.DTHRFIMMOV,'DD/MM/YYYY') AS DATA,
													 TO_CHAR(M.DTHRFIMMOV,'HH24:MM:SS.FF') AS HORA, M.VRMOV AS VALOR,
													 I.DSBUTTON AS BANDEIRA, M.IDTIPMOV AS IDTIPORECE, M.IDTPTEF,
													 M.NRADMCODE, M.DSEMAILCLI, M.NRSEQMOVMOB,  M.DTHRFIMMOV,
													 T.CDBANCARTCR, T.IDDESABTEF, V.NRSEQVENDA, V.IDSITUVENDA
											FROM MOVCAIXAMOB M JOIN TIPORECE T
																					 ON M.CDTIPORECE = T.CDTIPORECE
																		LEFT JOIN ITMENUCONFTE I
																					 ON I.CDIDENTBUTON = T.CDTIPORECE
																				 JOIN CAIXA C
																					 ON C.CDCAIXA = M.CDCAIXA
																					AND C.CDFILIAL = M.CDFILIAL
																		LEFT JOIN VENDA V
																					 ON V.CDCAIXA = M.CDCAIXA
																					AND V.CDFILIAL = M.CDFILIAL
																					AND V.NRSEQVENDA = M.NRSEQVENDA
										 WHERE ((M.DTHRFIMMOV BETWEEN ? AND ?) OR M.NRADMCODE = ?)
											 AND M.IDSTMOV = 1
											 AND M.IDADMTASK = 0
											 AND M.CDFILIAL = ?
											 AND M.CDCAIXA = ?
											 AND I.NRCONFTELA = C.NRCONFTELA
								) D
						) A
				WHERE A.N BETWEEN ? AND ?
		";

		const SQL_BUSCA_TRANSACOES_ENTRADA_MOVCAIXA = "
				SELECT SUM(MC.VRMOVIVEND) AS VALORPAGO
					FROM MOVCAIXA MC
					JOIN VENDA V
						ON  (MC.NRSEQVENDA   = V.NRSEQVENDA)
						AND (MC.CDFILIAL     = V.CDFILIAL)
						AND (MC.CDCAIXA      = V.CDCAIXA)
						AND (MC.NRORG        = V.NRORG)
						AND (MC.IDTIPOMOVIVE = 'E')
					JOIN VENDAREST VR
						ON  (V.CDFILIAL    = VR.CDFILIAL)
						AND (V.NRVENDAREST = VR.NRVENDAREST)
						AND (V.NRMESA      = VR.NRMESA)
						AND (V.NRORG       = VR.NRORG)
					WHERE VR.NRVENDAREST IN (:NRVENDAREST)
						AND VR.CDFILIAL    = :CDFILIAL
		";

		const SQL_BUSCA_TRANSACOES_SAIDA_MOVCAIXA = "
				SELECT SUM(MC.VRMOVIVEND) AS VALORRETIRADA
					FROM MOVCAIXA MC
					JOIN VENDA V
						ON  (MC.NRSEQVENDA   = V.NRSEQVENDA)
						AND (MC.CDFILIAL     = V.CDFILIAL)
						AND (MC.CDCAIXA      = V.CDCAIXA)
						AND (MC.NRORG        = V.NRORG)
						AND (MC.IDTIPOMOVIVE = 'S')
					JOIN VENDAREST VR
						ON  (V.CDFILIAL    = VR.CDFILIAL)
						AND (V.NRVENDAREST = VR.NRVENDAREST)
						AND (V.NRMESA      = VR.NRMESA)
						AND (V.NRORG       = VR.NRORG)
					WHERE VR.NRVENDAREST IN (:NRVENDAREST)
						AND VR.CDFILIAL    = :CDFILIAL
		";

		const SQL_BUSCA_TRANSACOES_MESA_MOVCAIXAMOB = "
				SELECT SUM(VRMOV) AS VALORPAGO
						FROM MOVCAIXAMOB
				WHERE CDFILIAL = :CDFILIAL
						AND NRVENDAREST IN (:NRVENDAREST)
						AND IDSTMOV = '1'
						AND IDADMTASK = 0
		";

		const SQL_BUSCA_TRANSACOES_POSICAO_MOVCAIXAMOB = "
				SELECT *
						FROM MOVCAIXAMOB
				WHERE CDFILIAL = :CDFILIAL
						AND NRVENDAREST IN (:NRVENDAREST)
						AND (NRLUGARMESA IN (:NRLUGARMESA) OR NRLUGARMESA = 'T')
						AND IDSTMOV = '1'
						AND IDADMTASK = '0'
		";

		const SQL_DADOS_ITEM_COMANDA = "
				SELECT
			DISTINCT CDFILIAL, NRVENDAREST, NRCOMANDA, NRPRODCOMVEN,
							 CDPRODUTO, QTPRODCOMVEN, VRPRECCOMVEN, TO_CHAR(TXPRODCOMVEN) AS TXPRODCOMVEN,
							 IDSTPRCOMVEN, VRDESCCOMVEN, NRLUGARMESA, CDGRPOCOR,
							 CDOCORR, NRMESAORIG, CDLOJAORIG, DTHRINCOMVEN,
							 IDPRODIMPFIS, CDLOJA, NRSEQPRODCOM, NRSEQPRODCUP,
							 VRACRCOMVEN, DSCOMANDAORI, NRCOMANDAORI, NRPRODCOMORI,
							 CDCAIXACOLETOR, VRPRECCLCOMVEN, NRMESADSCOMORIT, CDVENDEDOR,
							 CDPRODPROMOCAO, NRPEDIDOFOS, CDSENHAPED, NRATRAPRODCOVE, IDORIGPEDCMD,
							 TO_CHAR(DSOBSPEDDIGCMD) AS DSOBSPEDDIGCMD, IDPRODREFIL, QTITEMREFIL, IDDIVIDECONTA
					FROM (SELECT
							DISTINCT CDFILIAL, NRVENDAREST, NRCOMANDA, NRPRODCOMVEN,
											 CDPRODUTO, QTPRODCOMVEN, VRPRECCOMVEN, TO_CHAR(TXPRODCOMVEN) AS TXPRODCOMVEN,
											 IDSTPRCOMVEN, VRDESCCOMVEN, NRLUGARMESA, CDGRPOCOR,
											 CDOCORR, NRMESAORIG, CDLOJAORIG, DTHRINCOMVEN,
											 IDPRODIMPFIS, CDLOJA, NRSEQPRODCOM, NRSEQPRODCUP,
											 VRACRCOMVEN, DSCOMANDAORI, NRCOMANDAORI, NRPRODCOMORI,
											 CDCAIXACOLETOR, VRPRECCLCOMVEN, NRMESADSCOMORIT, CDVENDEDOR,
											 CDPRODPROMOCAO, NRPEDIDOFOS, CDSENHAPED, NRATRAPRODCOVE, IDORIGPEDCMD,
											 TO_CHAR(DSOBSPEDDIGCMD) AS DSOBSPEDDIGCMD, IDPRODREFIL, QTITEMREFIL, IDDIVIDECONTA
									FROM ITCOMANDAVEN
								 WHERE CDFILIAL     = ?
									 AND NRVENDAREST  = ?
									 AND NRCOMANDA    = ?
									 AND NRPRODCOMVEN = ?

								 UNION

								SELECT
							DISTINCT CDFILIAL, NRVENDAREST, NRCOMANDA, NRPRODCOMVEN,
											 CDPRODUTO, QTPRODCOMVEN, VRPRECCOMVEN, TO_CHAR(TXPRODCOMVEN) AS TXPRODCOMVEN,
											 IDSTPRCOMVEN, VRDESCCOMVEN, NRLUGARMESA, CDGRPOCOR,
											 CDOCORR, NRMESAORIG, CDLOJAORIG, DTHRINCOMVEN,
											 IDPRODIMPFIS, CDLOJA, NRSEQPRODCOM, NRSEQPRODCUP,
											 VRACRCOMVEN, DSCOMANDAORI, NRCOMANDAORI, NRPRODCOMORI,
											 CDCAIXACOLETOR, VRPRECCLCOMVEN, NRMESADSCOMORIT, CDVENDEDOR,
											 CDPRODPROMOCAO, NRPEDIDOFOS, CDSENHAPED, NRATRAPRODCOVE, IDORIGPEDCMD,
											 TO_CHAR(DSOBSPEDDIGCMD) AS DSOBSPEDDIGCMD, IDPRODREFIL, QTITEMREFIL, IDDIVIDECONTA
									FROM ITCOMANDAVEN
								 WHERE CDFILIAL     = ?
									 AND NRVENDAREST  = ?
									 AND NRCOMANDA    = ?
									 AND NRSEQPRODCOM = ?
									 AND NRSEQPRODCOM IS NOT NULL) A
		";

		const SQL_INSERE_LOG = "
				INSERT INTO LOGOPERFOS
						(CDFILIAL, CDCAIXA, IDOPERFOS, CDOPERCAIXA, NMOPERCAIXA,
						CDOPERRESPOP, NMOPERRESPOP, DTHROPERFOS,  DSMOTIVOFOS, DSLIVREFOS)
				VALUES
						(?, ?, ?, ?, ?,
						 ?, ?, SYSDATE, ?, ?)
		";

		const SQL_DADOS_COMANDA_ABERTURA = "
				SELECT C.DSCOMANDA, C.NRVENDAREST, C.NRCOMANDA, C.IDSTCOMANDA,
							 V.CDLOJA, V.NRMESA, C.VRDESCOMANDA, C.VRCOMISVENDE,
							 C.VRACRCOMANDA, V.CDVENDEDOR, V.CDCLIENTE, V.CDCONSUMIDOR, CO.NMCONSUMIDOR,
							 C.DSCOMANDA || (CASE WHEN NVL(C.DSCONSUMIDOR, CO.NMCONSUMIDOR) IS NULL THEN '' ELSE ' - ' END) ||
							 NVL(NVL(C.DSCONSUMIDOR, CO.NMCONSUMIDOR), '') AS LABELDSCOMANDA
					FROM COMANDAVEN C JOIN VENDAREST V
															ON C.CDFILIAL    = V.CDFILIAL
														 AND C.NRVENDAREST = V.NRVENDAREST
														 AND C.CDLOJA      = V.CDLOJA
											 LEFT JOIN CONSUMIDOR CO
															ON V.CDCLIENTE = CO.CDCLIENTE
														 AND V.CDCONSUMIDOR = CO.CDCONSUMIDOR
				WHERE C.CDFILIAL = :CDFILIAL
					AND C.DSCOMANDA = :DSCOMANDA
					AND C.CDLOJA = :CDLOJA
					AND C.IDSTCOMANDA <> '4'
		";


		const SQL_FILIAIS = "
				SELECT A.FILIAL, A.CDFILIAL, A.NMFILIAL FROM(
						SELECT ROWNUM AS ROWNUM_, CDFILIAL || ' - ' || NMFILIAL AS FILIAL,
									 CDFILIAL, NMFILIAL
							FROM FILIAL
						 WHERE CDFILIAL || ' - ' || NMFILIAL LIKE :FILIAL
					ORDER BY CDFILIAL
				) A
				WHERE ROWNUM BETWEEN :P_BEGIN AND :P_END
		";

		const SQL_CAIXAS = "
				SELECT A.CAIXA, A.CDFILIAL, A.CDCAIXA, A.NMCAIXA
					FROM (
						SELECT ROWNUM AS ROWNUM_, CDCAIXA || ' - ' || NMCAIXA AS CAIXA,
									 CDFILIAL, CDCAIXA, NMCAIXA
							FROM CAIXA
						 WHERE CDFILIAL = :CDFILIAL
							 AND CDCAIXA || ' - ' || NMCAIXA LIKE :CAIXA
							 AND IDHABCAIXAVENDA IN ('PKC', 'PKR', 'FOS', 'POS')
						 ORDER BY CDCAIXA
				) A
				 WHERE ROWNUM BETWEEN :P_BEGIN AND :P_END

		";

		const SQL_VENDEDORES = "
				SELECT B.GARCOM, B.CDFILIAL, B.CDCAIXA, B.CDOPERADOR, B.CDVENDEDOR, B.NMFANVEN FROM (
					SELECT ROWNUM AS ROWNUM_, A.GARCOM, A.CDFILIAL, A.CDCAIXA, A.CDOPERADOR, A.CDVENDEDOR, A.NMFANVEN FROM(
						SELECT DISTINCT VE.CDVENDEDOR ||' - '|| VE.NMFANVEN AS GARCOM, VE.CDFILIAL, O.CDOPERADOR, VE.CDVENDEDOR, VE.CDCAIXA, VE.NMFANVEN
							FROM VENDEDOR VE JOIN OPERADOR O
																 ON O.CDOPERADOR = VE.CDOPERADOR
															 JOIN FILIAL F
																 ON VE.CDFILIAL = F.CDFILIAL
															 JOIN OPERGRUPOP OP
																 ON OP.CDOPERADOR = O.CDOPERADOR
															 JOIN GRUPOPER GP
																 ON GP.CDGRUPOPER = OP.CDGRUPOPER
															 JOIN FILIOPER FP
																 ON F.CDFILIAL = FP.CDFILIAL
																AND O.CDOPERADOR = FP.CDOPERADOR
						 WHERE VE.CDFILIAL = :CDFILIAL
							AND VE.CDVENDEDOR || ' - ' || VE.NMFANVEN LIKE :GARCOM
					ORDER BY CDVENDEDOR
						) A )B
						WHERE ROWNUM BETWEEN :P_BEGIN AND :P_END
		";

		const SQL_GET_PRODUCT_DESC = "
				SELECT NVL(I.DSBUTTON, P.NMPRODUTO) AS DESCPROD
					FROM PRODUTO P LEFT JOIN ITMENUCONFTE I
																ON P.CDPRODUTO = I.CDIDENTBUTON
															AND I.CDFILIAL = :CDFILIAL
															AND I.NRCONFTELA = :NRCONFTELA
															AND I.IDTPBUTTON = '1'
				WHERE P.CDPRODUTO = :CDPRODUTO
		";

		const SQL_BUSCA_CONSUMIDORES = "
				SELECT D.* FROM(
						SELECT ROW_NUMBER() OVER (ORDER BY C.CDCONSUMIDOR) AS ROWNUMBER, C.CDCLIENTE, CL.NMRAZSOCCLIE,
									 C.CDCONSUMIDOR, C.NMCONSUMIDOR, C.CDIDCONSUMID, NVL(C.NRCPFRESPCON, '') AS NRCPFRESPCON,
									 C.IDSITCONSUMI, T.IDSOLSENHCONS, C.CDSENHACONS
							FROM CONSUMIDOR C
							JOIN CLIENTE CL ON C.CDCLIENTE = CL.CDCLIENTE
							JOIN TIPOCONS T ON T.CDTIPOCONS = C.CDTIPOCONS
						 WHERE (UPPER(C.CDCONSUMIDOR) LIKE :CDCONSUMIDOR
								OR UPPER(C.NMCONSUMIDOR) LIKE :CDCONSUMIDOR
								OR NVL(C.CDIDCONSUMID, '') LIKE :CDCONSUMIDOR
								OR NVL(C.NRCPFRESPCON, '') LIKE :CDCONSUMIDOR
								OR NVL(C.CDEXCONSUMID, '') LIKE :CDCONSUMIDOR)
							 AND (T.IDDESABPESQCON = 'N' OR :CONSBLOBQ = 'S')
							 AND (CL.CDCLIENTE = :CDCLIENTE OR 'T' = :CDCLIENTE)
							 AND (:ALLCONSU = 'T' OR C.IDSITCONSUMI = '1')
							 AND C.CDCLIENTE IN (SELECT CDCLIENTE FROM CLIENFILIAL WHERE CDFILIAL = :CDFILIAL)
				) D
				WHERE D.ROWNUMBER BETWEEN :FIRST AND :LAST
		";

		const SQL_CONSUMER_CDEXCONSUMID = "
				SELECT CO.CDCLIENTE, CO.CDCONSUMIDOR, CO.NMCONSUMIDOR, CL.NMRAZSOCCLIE, CO.CDIDCONSUMID, NVL(CO.NRCPFRESPCON, '') AS NRCPFRESPCON
					FROM CONSUMIDOR CO
					JOIN CLIENTE CL ON CL.CDCLIENTE = CO.CDCLIENTE
				 WHERE (CO.CDCLIENTE = :CDCLIENTE OR :CDCLIENTE = 'T')
					 AND CO.CDEXCONSUMID = :code
					 AND CO.IDSITCONSUMI = '1'
		";

		const SQL_CONSUMER_CDIDCONSUMID = "
				SELECT CO.CDCLIENTE, CO.CDCONSUMIDOR, CO.NMCONSUMIDOR, CL.NMRAZSOCCLIE, CO.CDIDCONSUMID, NVL(CO.NRCPFRESPCON, '') AS NRCPFRESPCON
					FROM CONSUMIDOR CO
					JOIN CLIENTE CL ON CL.CDCLIENTE = CO.CDCLIENTE
				 WHERE (CO.CDCLIENTE = :CDCLIENTE OR :CDCLIENTE = 'T')
					 AND CO.CDIDCONSUMID = :code
					 AND CO.IDSITCONSUMI = '1'
		";

		const SQL_CONSUMER_NRCPFRESPCON = "
				SELECT CO.CDCLIENTE, CO.CDCONSUMIDOR, CO.NMCONSUMIDOR, CL.NMRAZSOCCLIE, CO.CDIDCONSUMID, NVL(CO.NRCPFRESPCON, '') AS NRCPFRESPCON
					FROM CONSUMIDOR CO
					JOIN CLIENTE CL ON CL.CDCLIENTE = CO.CDCLIENTE
				 WHERE (CO.CDCLIENTE = :CDCLIENTE OR :CDCLIENTE = 'T')
					 AND CO.NRCPFRESPCON = :code
					 AND CO.IDSITCONSUMI = '1'
		";

		const SQL_GET_CONSUMER_DETAILS = "
				SELECT CO.CDCLIENTE, CO.CDCONSUMIDOR, CO.CDIDCONSUMID, CO.NMCONSUMIDOR, CO.IDTPVENDACONS, CO.CDSENHACONS,
							 CO.DSEMAILCONS, CO.NRCELULARCONS, CO.NRTELECONS, CL.NMRAZSOCCLIE, CO.CDIDCONSUMID, NVL(CO.NRCPFRESPCON, '') AS NRCPFRESPCON
					FROM CONSUMIDOR CO
					JOIN CLIENTE CL ON CL.CDCLIENTE = CO.CDCLIENTE
				 WHERE (CO.CDCLIENTE = :CDCLIENTE OR :CDCLIENTE = 'T')
					 AND CO.CDCONSUMIDOR = :code
					 AND CO.IDSITCONSUMI = '1'
		";

		const GET_ULTIMA_VENDA_FISCAL = "
			SELECT MAX(NRNOTAFISCALCE) AS NRNOTAFISCALCE
					FROM VENDA
				 WHERE CDFILIAL = :CDFILIAL
					 AND CDCAIXA = :CDCAIXA
					 AND NRORG = :NRORG
					 AND (CDSERIENFCE = :CDSERIENFCE OR 'SAT' = :CDSERIENFCE)
					 AND IDSITUVENDA <> 'C'
					 AND IDTPEMISVEND = :IDTPEMISVEND
					 AND TO_CHAR(DTEMISSAONFCE, 'YYYY-MM-DD') = :DTEMISSAONFCE
		";

		const GET_VENDA = "
				SELECT *
					FROM VENDA
				 WHERE CDFILIAL = :CDFILIAL
					 AND CDCAIXA = :CDCAIXA
					 AND NRORG = :NRORG
					 AND NRNOTAFISCALCE = :NRNOTAFISCALCE
					 AND (CDSERIENFCE = :CDSERIENFCE OR 'SAT' = :CDSERIENFCE)
					 AND IDSITUVENDA <> 'C'
					 AND TO_CHAR(DTEMISSAONFCE, 'YYYY-MM-DD') = :DTEMISSAONFCE
		";

		const SQL_CHECK_ORDERCODE = "
				SELECT CDORDERWAITER, DSOPERACAO, IDSTORDER, DTHRINCREQ
					FROM WAITERORDERS
				 WHERE CDFILIAL = :CDFILIAL
					 AND NRVENDAREST = :NRVENDAREST
					 AND NRCOMANDA = :NRCOMANDA
					 AND CDORDERWAITER = :CDORDERWAITER
		";

		const SQL_BUSCA_CARTOES = "
				SELECT C.CDCLIENTE || '-' || C.CDCONSUMIDOR || '-' || NVL(C.CDFAMILISALD, '') AS ID,
							 C.CDCLIENTE, C.NMFANTCLIE, C.CDCONSUMIDOR, C.NMCONSUMIDOR,
							 C.CDIDCONSUMID, NVL(E.VRSALDCONEXT,0) AS VRSALDCONEXT,
							 C.CDFAMILISALD, FA.NMFAMILISALD, C.IDPERTRANSALD, C.CDTIPOCONS, C.NMTIPOCONS
					FROM EXTRATOCONS E
				 RIGHT JOIN (SELECT MAX(DTMOVEXTCONS) AS DTMOVEXTCONS, C.CDCLIENTE, C.CDIDCONSUMID,
														C.CDCONSUMIDOR, C.NMCONSUMIDOR, C.NMFANTCLIE, E.CDFAMILISALD,
														C.IDPERTRANSALD, C.CDTIPOCONS, C.NMTIPOCONS
											 FROM EXTRATOCONS E
											RIGHT JOIN (SELECT CO.CDCLIENTE,CO.CDCONSUMIDOR,CO.NMCONSUMIDOR,CO.CDIDCONSUMID,
																				 CL.NMFANTCLIE, TC.IDPERTRANSALD, CO.CDTIPOCONS, TC.NMTIPOCONS
																		FROM CONSUMIDOR CO
																		JOIN CLIENTE CL ON CO.CDCLIENTE = CL.CDCLIENTE
																		LEFT JOIN TIPOCONS TC ON CO.CDTIPOCONS = TC.CDTIPOCONS
																	 WHERE (CDIDCONSUMID = :SEARCH_VALUE OR CDEXCONSUMID = :SEARCH_VALUE)
																	) C ON E.CDCLIENTE = C.CDCLIENTE
																		 AND E.CDCONSUMIDOR = C.CDCONSUMIDOR
											GROUP BY C.CDCLIENTE, C.CDIDCONSUMID, C.NMCONSUMIDOR, C.CDCONSUMIDOR, C.NMFANTCLIE,
															 E.CDFAMILISALD, C.IDPERTRANSALD, C.CDTIPOCONS, C.NMTIPOCONS
										) C ON E.CDCLIENTE    = C.CDCLIENTE
											 AND E.CDCONSUMIDOR = C.CDCONSUMIDOR
											 AND E.DTMOVEXTCONS = C.DTMOVEXTCONS
											 AND E.CDFAMILISALD = C.CDFAMILISALD
											 AND E.NRSEQMOVEXT  = (SELECT MAX(NRSEQMOVEXT) AS NRSEQMOVEXT
																							 FROM EXTRATOCONS
																							WHERE CDCLIENTE    = C.CDCLIENTE
																								AND CDCONSUMIDOR = C.CDCONSUMIDOR
																								AND DTMOVEXTCONS = C.DTMOVEXTCONS
																								AND CDFAMILISALD = C.CDFAMILISALD)
					LEFT JOIN FAMILIASALDO FA ON E.CDFAMILISALD = FA.CDFAMILISALD
		";

		const FILTRAR_PRODUTOS = "
				SELECT D.* FROM(
						SELECT ROW_NUMBER() OVER (ORDER BY PR.CDPRODUTO) AS ROWNUMBER,
							 PR.CDPRODUTO, PR.CDARVPROD, NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO)) AS DSBUTTON,
							 PR.CDBARPRODUTO, PR.IDPESAPROD, PR.QTTARAPROD, '' AS CDFAMILISALD, PR.SGUNIDADE, PR.IDTIPOCOMPPROD,
							 PR.IDIMPPRODUTO, PR.DTINIVGPROMOC, PR.DTFINVGPROMOC, IT.HRINIVENPROD, IT.HRFIMVENPROD,
							 IT.VRPRECITEM, NVL(IT.VRPRECITEMCL, 0) AS VRPRECITEMCL, IT.VRPRECITEM AS PRECO, IT.VRPRECITEM AS PRITEM, '0' AS GRUPOS,
							 CASE WHEN PB.CDPRODUTO IS NULL THEN PR.IDPRODBLOQ ELSE 'S' END AS IDPRODBLOQ,
							 NVL(IM.NRPGCONFTAUX||IM.NRBUTTONAUX, '000') AS CDGRUPO, NVL(G.NMGRUPO, 'OUTROS') AS NMGRUPO,
							 PR.IDTIPOPROD, PR.NRQTDMINOBS, null AS IDTIPCOBRA, PR.CDPRODINTE, PR.CDPROTECLADO, PR.DSPRODVENDA,
							 PR.CDCLASFISC, AL.CDCFOPPFIS, AL.CDCSTICMS, AL.VRALIQPIS, AL.CDCSTPISCOF, AL.VRALIQCOFINS, 0 AS VRDESITVEND, 0 AS VRACRITVEND, PR.IDCONTROLAREFIL AS REFIL
						FROM
							 PARAVEND PA JOIN TABEVEND TA
														 ON ((PA.CDFILIAL   = :CDFILIAL)
														AND  (PA.CDFILIAL   = TA.CDFILIAL)
														AND  (PA.CDTABEPREC = TA.CDTABEPREC)
														AND  (:DATAATUAL BETWEEN TA.DTINIVGPREC AND TA.DTFINVGPREC))
													 JOIN ITEMPRECO IT
														 ON ((IT.CDFILIAL    = TA.CDFILIAL)
														AND  (IT.CDTABEPREC  = TA.CDTABEPREC)
														AND  (IT.DTINIVGPREC = TA.DTINIVGPREC))
													 JOIN PRODUTO PR
														 ON ((PR.CDPRODUTO = IT.CDPRODUTO))
													 LEFT JOIN PRODBLOQVND PB
														 ON PB.CDPRODUTO = PR.CDPRODUTO
														 AND PB.CDFILIAL = PA.CDFILIAL
														 AND PB.CDLOJA = :CDLOJA
													 LEFT JOIN ITMENUCONFTE IM
														 ON IM.CDFILIAL = PA.CDFILIAL
														 AND IM.NRCONFTELA = :NRCONFTELA
														 AND IM.CDIDENTBUTON = PR.CDPRODUTO
													 INNER JOIN ALIQIMPFIS AL
														 ON AL.CDFILIAL = PA.CDFILIAL
														 AND AL.CDPRODUTO = PR.CDPRODUTO
													 LEFT JOIN (SELECT NRPGCONFTELA, NRBUTTON, DSBUTTON AS NMGRUPO
																				FROM (SELECT AM.IDTPBUTTON, AM.IDTPBUTONAUX, AM.NRBUTTON, AM.NRBUTTONAUX,
																											AM.DSBUTTON, AM.CDIDENTBUTON, AM.NRCOLORTEXT, AM.NRCOLORBACK,
																											AM.NRPGCONFTELA, AM.NRPGCONFTAUX, AM.DSMESSAGEBUT, AM.DSIMAGEMBUT,
																											AM.DSENDEIMG
																								FROM ITMENUCONFTE AM
																								WHERE AM.CDFILIAL   = :CDFILIAL
																									AND AM.NRCONFTELA = :NRCONFTELA) MESA,
																					PARAMGERAL P
																				WHERE IDTPBUTTON = '2') G
														 ON G.NRPGCONFTELA = IM.NRPGCONFTAUX
														 AND G.NRBUTTON = IM.NRBUTTONAUX

						WHERE
							 (CDNVPRODUTO = (SELECT
																	MAX(CDNVPRODUTO) FROM PRODUTO))
						AND ((0 = :SEARCH AND (PR.CDARVPROD LIKE :FILTER
																OR PR.CDPRODUTO LIKE :FILTER
																OR PR.CDBARPRODUTO LIKE :FILTER
																OR PR.CDPRODINTE LIKE :FILTER
																OR PR.CDPROTECLADO LIKE :FILTER
																OR NVL(IM.DSBUTTON, NVL(PR.NMPRODIMPFIS, PR.NMPRODUTO)) LIKE :FILTER))
						OR (1 = :SEARCH AND (PR.CDARVPROD = :FILTER
															OR PR.CDPRODUTO = :FILTER
															OR PR.CDBARPRODUTO = :FILTER
															OR PR.CDPRODINTE = :FILTER
															OR PR.CDPROTECLADO = :FILTER)))

				) D
				WHERE D.ROWNUMBER BETWEEN :FIRST AND :LAST
		";

		const GET_VENDAS = "
				SELECT NRNOTAFISCALCE, DTVENDA, VRTOTVENDA
					FROM VENDA
				WHERE CDFILIAL = :CDFILIAL
					AND CDCAIXA = :CDCAIXA
					AND TO_CHAR(DTABERTUR, 'YYYY-MM-DD HH24:MI:SS') = :DTABERCAIX
					AND NRNOTAFISCALCE LIKE :FILTER
					AND IDSITUVENDA <> 'C'
				ORDER BY NRSEQVENDA DESC
		";

		const SQL_COMANDA_ITENS = "
				SELECT PR.CDARVPROD, PR.NMPRODUTO, PR.CDPRODUTO, IT.NRPRODCOMVEN, IT.CDPRODPROMOCAO, IT.NRSEQPRODCOM,
				PR.CDPRODUTO||'-'||NVL(IT.NRSEQPRODCOM, '') AS VALOR
					FROM ITCOMANDAVEN IT, PRODUTO PR
				 WHERE IT.CDFILIAL = :CDFILIAL
					 AND IT.NRCOMANDA = :NRCOMANDA
					 AND IT.CDPRODUTO = PR.CDPRODUTO
					 AND IT.IDSTPRCOMVEN <> '6'
			";

		const BUSCA_DADOS_CAMPANHA = "
				SELECT P.CDCAMPPROMO, P.CDPRODPRIN, P.CDPRODCOMB, P.IDPERCVALOR, P.IDDESCACRE,
							 P.VRDESCACRE, P.IDAPLICADESACR, P.CDPRODCOMB2, P.CDPRODCOMB3, C.CDCLIENTE
					FROM CAMPANHAPROMO C, COMBINAPROD P
				 WHERE SYSDATE BETWEEN C.DTINIVGCAMP AND C.DTFINVGCAMP
					 AND :HORA BETWEEN C.HRINICAMP AND C.HRFINCAMP
					 AND :HORA BETWEEN P.HRINICOMB AND P.HRFINCOMB
					 AND ((TO_CHAR(SYSDATE, 'D') = '1' AND C.IDDIADOMINGO = 'S' AND P.IDDIADOMCOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '2' AND C.IDDIASEGUNDA = 'S' AND P.IDDIASEGCOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '3' AND C.IDDIATERCA   = 'S' AND P.IDDIATERCOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '4' AND C.IDDIAQUARTA  = 'S' AND P.IDDIAQUACOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '5' AND C.IDDIAQUINTA  = 'S' AND P.IDDIAQUICOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '6' AND C.IDDIASEXTA   = 'S' AND P.IDDIASEXCOMB = 'S') OR
							 (TO_CHAR(SYSDATE, 'D') = '7' AND C.IDDIASABADO  = 'S' AND P.IDDIASABCOMB = 'S'))
					 AND CASE WHEN (:CDTIPOCONS IS NULL) THEN
							 CASE WHEN C.CDTIPOCONS IS NULL THEN 1 ELSE 0 END
							 ELSE
							 CASE WHEN C.CDCLIENTE = :CDCLIENTE AND C.CDTIPOCONS = :CDTIPOCONS THEN 1 ELSE 0 END
					 END = 1
					 AND C.CDCAMPPROMO = P.CDCAMPPROMO
					 AND INSTR(P.CDPRODPRIN, :STRPRODUCTS) <> 0
					 AND INSTR(P.CDPRODCOMB, :STRPRODUCTS) <> 0
					 AND (INSTR(P.CDPRODCOMB2, :STRPRODUCTS) <> 0 OR P.CDPRODCOMB2 IS NULL)
					 AND (NOT EXISTS (SELECT 1
															FROM PRODUTO A
														 WHERE INSTR(A.CDPRODUTO, P.CDPRODCOMB3) <> 0
															 AND INSTR(A.CDPRODUTO, :STRPRODUCTS) = 0) OR P.CDPRODCOMB3 IS NULL)
				 ORDER BY P.VRDESCACRE DESC
		";

		const GET_REGISTER_CLOSING_PAY_N = "
				SELECT M.CDTIPORECE, T.NMTIPORECE, 0 AS VRMOVIVEND,
							 NULL AS LABELVRMOVIVEND, T.IDSANGRIAAUTO
					FROM TIPORECE T
					JOIN MOVCAIXA M ON T.CDTIPORECE = M.CDTIPORECE
				 WHERE M.CDFILIAL   = :CDFILIAL
					 AND M.CDCAIXA    = :CDCAIXA
					 AND M.IDTIPOMOVIVE IN ('E','T','U')
					 AND T.IDSANGRIAAUTO = 'N'
					 AND DTABERCAIX = TO_DATE(:DTABERCAIX, 'YYYY-MM-DD HH24:MI:SS')
				 GROUP BY M.CDTIPORECE, T.NMTIPORECE, T.IDSANGRIAAUTO
		";

		const GET_DELIVERY_ORDERS = "
			SELECT DISTINCT P.CDFILIAL, P.CDLOJA,
								IDSTCOMANDA, P.NRVENDAREST, DTHRABERMESA, CDCONSUMIDOR, NMCONSUMIDOR,
								NRTELECONS, P.NRCOMANDA, SUBSTR(DSCOMANDA, 5, 100) DSCOMANDA, CDCLIENTE, NRCPFRESPCON,
								CDMUNICIPIO, CDPAIS, SGESTADO, CDBAIRRO, DSBAIRRO, DSENDECONSCOMAN,
								DSCOMPLENDCOCOM,NRCEPCONSCOMAND, DSREFENDCONSCOM, DTENTREGA,
								NRVENDARESTAUX, IDORGCMDVENDA, CDNSUESITEF, IDRETBALLOJA, I.CDSENHAPED,
								P.VRACRCOMANDA, NRENDECONSCOMAN, NRCOMANDAEXT
					FROM (SELECT CO.CDFILIAL, CO.CDLOJA,
											 CO.IDSTCOMANDA, CO.NRVENDAREST, (TO_CHAR(DTHRABERMESA, 'dd/mm/yy hh24:mi:ss')) DTHRABERMESA, CS.CDCONSUMIDOR,
											 CS.NMCONSUMIDOR, CS.NRTELECONS, CO.NRCOMANDA, CO.DSCOMANDA, VE.CDCLIENTE,
											 CS.NRCPFRESPCON,CO.CDMUNICIPIO, MU.NMMUNICIPIO, CO.CDPAIS, CO.SGESTADO, CO.CDBAIRRO,
											 CO.DSBAIRRO, CO.DSENDECONSCOMAN, CO.DSCOMPLENDCOCOM, CO.NRCEPCONSCOMAND,
											 CAST(CO.DSREFENDCONSCOM AS VARCHAR(2000)) AS DSREFENDCONSCOM, CO.DTENTREGA,
											 VE.NRVENDARESTAUX, CO.IDORGCMDVENDA, VE.CDNSUESITEF, CO.IDRETBALLOJA, CO.VRACRCOMANDA, CO.NRENDECONSCOMAN, CO.NRCOMANDAEXT
									FROM COMANDAVEN CO, MUNICIPIO MU, VENDAREST VE
												LEFT JOIN CONSUMIDOR CS
															 ON (VE.CDCLIENTE    = CS.CDCLIENTE)
															AND (VE.CDCONSUMIDOR = CS.CDCONSUMIDOR)
								 WHERE (CO.NRVENDAREST  = VE.NRVENDAREST)
									 AND (CO.CDFILIAL     = VE.CDFILIAL)
									 AND (CO.CDPAIS      = MU.CDPAIS)
									 AND (CO.SGESTADO    = MU.SGESTADO)
									 AND (CO.CDMUNICIPIO = MU.CDMUNICIPIO)
									 AND (VE.CDFILIAL     = :CDFILIAL)
									 AND (CO.CDLOJA       = :CDLOJA)
									 AND (CO.IDSTCOMANDA NOT IN ('5','X'))
									 AND (SUBSTR(CO.DSCOMANDA,1,4) = 'DLV_')) P, ITCOMANDAVEN I
				WHERE P.CDFILIAL    = I.CDFILIAL
					AND P.CDLOJA      = I.CDLOJA
					AND P.NRVENDAREST = I.NRVENDAREST
					AND P.NRCOMANDA   = I.NRCOMANDA
				ORDER BY P.DTHRABERMESA DESC
		";

		const GET_DELIVERY_ORDERS_CONTROL = "
			SELECT VE.CDFILIAL, VE.CDCAIXA, VE.NRSEQVENDA, CO.IDSTCOMANDA,
				 (TO_CHAR(VE.DTSAIDAVENDA, 'dd/mm/yy hh24:mi:ss')) DTSAIDAVENDA,
				 (TO_CHAR(VE.DTCHEGAVENDA, 'dd/mm/yy hh24:mi:ss')) DTCHEGAVENDA,
				 VD.NRINSJURVEN, VD.NMFANVEN, MU.NMMUNICIPIO, RG.CDREGIAOMUNI, RG.NMREGIAOMUNI,
				 VE.DSENDECONSVENDA, VE.SGESTADO, BA.CDBAIRRO, NVL(BA.NMBAIRRO, VE.DSBAIRRO) AS NMBAIRRO,
				 PA.NMPAIS, ES.NMESTADO, VE.NRCOMANDAVND, VE.CDCLIENTE, VE.CDCONSUMIDOR, CD.NMCONSUMIDOR,
				 VE.DSCOMPLENDCOVEN, (TO_CHAR(VE.DTVENDA, 'dd/mm/yy')) AS DTVENDA, CO.NRVENDAREST,
				 CAST(VE.DSREFENDCONSVEN AS VARCHAR(2000)) AS DSREFENDCONSVEN, SUBSTR(CO.DSCOMANDA, 5, 100) DSCOMANDA, VE.CDLOJA, VE.NRNOTAFISCALCE
			FROM
				 VENDA VE LEFT JOIN VENDEDOR VD ON (VE.CDVENDEDOR = VD.CDVENDEDOR),
				 CONSUMIDOR CD, PAIS PA, ESTADO ES, MUNICIPIO MU,
				 BAIRRO BA LEFT JOIN REGIAOMUNI RG ON (BA.CDPAIS      = RG.CDPAIS)
						       					  AND (BA.SGESTADO    = RG.SGESTADO)
												  AND (BA.CDMUNICIPIO = RG.CDMUNICIPIO)
												  AND (BA.CDREGIAOMUNI    = RG.CDREGIAOMUNI)
									 RIGHT JOIN COMANDAVEN CO ON (CO.CDPAIS      = BA.CDPAIS)
															 AND (CO.SGESTADO    = BA.SGESTADO)
															 AND (CO.CDMUNICIPIO = BA.CDMUNICIPIO)
															 AND (CO.CDBAIRRO    = BA.CDBAIRRO)
			 WHERE (VE.CDLOJA = :CDLOJA)
				 AND (VE.CDFILIAL = :CDFILIAL)
				 AND (VE.DTCHEGAVENDA IS NULL)
				 AND (VE.CDFILIAL = CO.CDFILIAL)
				 AND (VE.NRCOMANDAVND = CO.NRCOMANDA)
				 AND (VE.DSCOMANDAVND = CO.DSCOMANDA)
				 AND (VE.IDSITUVENDA='O')
				 AND (CO.IDSTCOMANDA IN ('P','5'))
				 AND (CO.CDPAIS      = PA.CDPAIS)
				 AND (CO.CDPAIS      = ES.CDPAIS)
				 AND (CO.SGESTADO    = ES.SGESTADO)
				 AND (CO.CDPAIS      = MU.CDPAIS)
				 AND (CO.SGESTADO    = MU.SGESTADO)
				 AND (CO.CDMUNICIPIO = MU.CDMUNICIPIO)
				 AND (VE.CDCLIENTE = CD.CDCLIENTE)
				 AND (VE.CDCONSUMIDOR = CD.CDCONSUMIDOR)
			 ORDER BY VE.NRCOMANDAVND


		";

		const GET_ORDER_PARAMS_DLV = "
			SELECT
	          min(IT.NRPRODCOMVEN) as NRPRODCOMVEN, SUM(IT.QTPRODCOMVEN) AS QTPRODCOMVEN, IT.VRPRECCOMVEN, sum(IT.VRDESCCOMVEN) as VRDESCCOMVEN,IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, IT.CDPRODUTO, IT.IDPRODIMPFIS,
	          IT.IDSTPRCOMVEN, IT.NRLUGARMESA,IT.CDGRPOCOR, IT.CDOCORR, IT.NRMESAORIG, IT.CDLOJAORIG,
	          PR.CDARVPROD , NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO) AS NMPRODUTO,
	          VR.CDVENDEDOR, VR.DTHRABERMESA, VR.DTHRFECHMESA,
	          CM.VRDESCOMANDA, '0000000000' AS NRCUPOMFIS, VR.CDOPERADOR, VR.CDLOJA,
	          IM.IDTPIMPOSFIS, AQ.VRPEALIMPFIS, AQ.CDIMPOSTO,
	          'V' AS IDTPFORPGVEN, FL.CDEMPRESA, CM.VRCOMISVENDE AS VRTXSERVICO,
	          CM.VRCONSUMAMIN AS VRCONSUMAMIN, IT.CDLOJA AS CDLOJAIT, PR.IDCOBTXSERV,
	          'NNN' AS IDCONFIGPROD, AC.VRACRCOMANDA,  SYSDATE AS DTABERCAIX,
	          '' AS NRMESA, '' AS NRSEQ, '' AS STCDALIQ, VR.CDCLIENTE, VR.CDCONSUMIDOR,  CM.DSCOMANDA,
	          FA.CDFAMILISALD, TO_CHAR('') AS CDSERVFILI, NVL(IT.NMCONSVEND,'CONSUMIDOR') AS NMCONSVEND,IT.NRINSCRCONS, PR.SGUNIDADE, OP.NMOPERADOR, IT.CDPRODPROMOCAO,
	          IT.VRPRECCLCOMVEN AS VRUNITVENDCL, 0.00 AS ACRESITEM, '000000' AS NRCONTCUPOMFISC, '' AS CDORDALIQIMPR,
	          0.00 AS VRALIQIMPR, NVL(IT.DSENDEVENDA,'') AS DSENDEVENDA, IT.NRMESADSCOMORIT, TO_CHAR('') AS NRORDEMVND,
	          TO_CHAR('') AS NRSERIEVND, TO_CHAR('') AS NRSUBSERIEVND, VR.NRCERVENDAREST, VR.NRCOOVENDAREST,
	          '' AS NRSEQPRODCUP, IT.VRACRCOMVEN, VR.NRPESMESAVEN, IT.CDVENDEDOR AS CDVENDEDORITEM, 0.00 AS VRREPIQUEVENDA,
	          '' AS NMLOJA, CAST(IT.TXPRODCOMVEN AS VARCHAR(2000)) AS TXPRODCOMVEN, PR.CDBARPRODUTO AS CDPRODIMPFIS,
	          '' AS NMCONSUMIDOR, '' AS CDEXCONSUMID, SYSDATE AS DTCHECKINPH, SYSDATE AS DTCHECKOUTPH, '' AS CDRESERVAPH, '' AS CDNATPRODUTO,
	          IT.IDORIGPEDCMD, IT.DTHRINCOMVEN, IT.CDCAIXACOLETOR, TO_CHAR(IT.DSOBSPEDDIGCMD) AS DSOBSPEDDIGITA, '' AS CDGRPOCORDESC, '' AS DSOBSDESC, '' AS CDSUPERVISOR,
	          IT.CDSENHAPED, TO_CHAR(CM.DSOBSCOMANDA) AS DSOBSCOMANDA, CM.NRCOMANDAEXT, CM.DTHRAGENDADA, CM.DSCUPOMPROMO, CM.IDEXTCONSAPP, CM.DSAREAATEND, '' DSOBSFINVEN
	        FROM
	           PRODUTO PR LEFT JOIN FAMSALDOPROD FA
	                      ON (PR.CDPRODUTO = FA.CDPRODUTO) AND
	                         (:CDFILIAL  = FA.CDFILIAL ),
	           VENDAREST VR LEFT JOIN OPERADOR OP
	                      ON (VR.CDOPERADOR = OP.CDOPERADOR),
	           COMANDAVEN CM, FILIAL FL, IMPOSTO IM,
	           ITCOMANDAVEN IT LEFT JOIN ALIQIMPFIS AQ
	                           ON (IT.CDFILIAL  = AQ.CDFILIAL ) AND
	                              (IT.CDPRODUTO = AQ.CDPRODUTO),
	           (SELECT
	               SUM(VRACRCOMANDA) AS VRACRCOMANDA
	            FROM
	               COMANDAVEN CO
	            WHERE
	               (CO.CDFILIAL = :CDFILIAL)
	            AND(INSTR(:NRCOMANDA, CO.NRCOMANDA) <> 0))AC
	        WHERE (IT.CDFILIAL    = :CDFILIAL    )
	          AND (IT.CDFILIAL    = FL.CDFILIAL    )
	          AND (INSTR(:NRCOMANDA, IT.NRCOMANDA) <> 0)
	          AND (IT.CDPRODUTO   = PR.CDPRODUTO   )
	          AND (IT.IDSTPRCOMVEN NOT IN ('6','7'))
	          AND (IT.CDFILIAL    = VR.CDFILIAL    )
	          AND (IT.NRVENDAREST = VR.NRVENDAREST )
	          AND (IT.CDFILIAL    = CM.CDFILIAL    )
	          AND (IT.NRCOMANDA   = CM.NRCOMANDA   )
	          AND (AQ.CDIMPOSTO   = IM.CDIMPOSTO   )
	          AND (IT.NRVENDAREST = VR.NRVENDAREST)
	        GROUP BY
	          IT.CDFILIAL, IT.NRVENDAREST, IT.NRCOMANDA, IT.CDPRODUTO, IT.IDPRODIMPFIS,
	          IT.IDSTPRCOMVEN, IT.VRPRECCOMVEN, IT.NRLUGARMESA,IT.CDGRPOCOR, IT.CDOCORR, IT.NRMESAORIG, IT.CDLOJAORIG,
	          PR.CDARVPROD ,  NMPRODUTO, NVL(PR.NMPRODIMPFIS,PR.NMPRODUTO),
	          VR.CDVENDEDOR, VR.DTHRABERMESA, VR.DTHRFECHMESA, CM.VRDESCOMANDA,   VR.CDOPERADOR, VR.CDLOJA,
	          IM.IDTPIMPOSFIS, AQ.VRPEALIMPFIS, AQ.CDIMPOSTO,  FL.CDEMPRESA,  CM.VRCOMISVENDE ,
	          VRCONSUMAMIN,IT.CDLOJA, PR.IDCOBTXSERV, AC.VRACRCOMANDA,  NRMESA,  VR.CDCLIENTE, VR.CDCONSUMIDOR,  CM.DSCOMANDA,
	          FA.CDFAMILISALD, NVL(IT.NMCONSVEND,'CONSUMIDOR'), IT.NRINSCRCONS, NVL(IT.DSENDEVENDA,''), PR.SGUNIDADE, OP.NMOPERADOR, IT.CDPRODPROMOCAO,IT.VRPRECCLCOMVEN,
	          IT.NRMESADSCOMORIT, VR.NRCERVENDAREST, VR.NRCOOVENDAREST,IT.VRACRCOMVEN, VR.NRPESMESAVEN, IT.CDVENDEDOR,
	          CAST(IT.TXPRODCOMVEN AS VARCHAR(2000)), PR.CDBARPRODUTO, IT.IDORIGPEDCMD, IT.DTHRINCOMVEN, IT.CDCAIXACOLETOR,
	          TO_CHAR(IT.DSOBSPEDDIGCMD), IT.CDSENHAPED, CM.DSOBSCOMANDA, CM.NRCOMANDAEXT, CM.DTHRAGENDADA, CM.DSCUPOMPROMO, CM.IDEXTCONSAPP, CM.DSAREAATEND
		";

	    const GET_PRODUTOS_PEDIDODLV = "
	        SELECT P.NMPRODUTO, IT.QTPRODCOMVEN, VRPRECCOMVEN,
	               (TRUNC((IT.VRPRECCOMVEN * IT.QTPRODCOMVEN), 2)  + IT.VRACRCOMVEN - IT.VRDESCCOMVEN) VRPRECCOMVENTOTAL,
	               IT.NRPRODCOMVEN, IT.CDPRODPROMOCAO, IT.NRSEQPRODCUP,
	               IT.NRSEQPRODCOM, IT.NRVENDAREST, IT.NRCOMANDA, IT.CDSUPERVISOR,
	               IT.IDPRODPRODUZ, IT.CDPRODUTO
	            FROM ITCOMANDAVEN IT, PRODUTO P
	        WHERE IT.CDFILIAL      = :CDFILIAL
	          AND IT.NRVENDAREST   = :NRVENDAREST
	          AND P.CDPRODUTO      = IT.CDPRODUTO
	          AND IT.IDSTPRCOMVEN  <> '6'
	    ";

	const UPDATE_VRCOMISVENDE = "
        UPDATE CDV
            SET CDV.VRCOMISVENDE = TRUNC((:PRECOTXTOTAL * (NVL(CDV.VRCOMISPOR, LOJ.VRCOMISVENDA) / 100)), 2)
        FROM COMANDAVEN CDV
        JOIN LOJA LOJ
          ON LOJ.CDFILIAL = CDV.CDFILIAL
         AND LOJ.CDLOJA = CDV.CDLOJA
         AND LOJ.NRORG = CDV.NRORG
        WHERE CDV.CDFILIAL = :CDFILIAL
            AND CDV.CDLOJA = :CDLOJA
            AND CDV.NRVENDAREST = :NRVENDAREST
            AND CDV.NRCOMANDA = :NRCOMANDA
    ";

}